//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAC1
    {
        public string Code { get; set; }
        public int LineNum { get; set; }
        public string DprAreaID { get; set; }
        public string Active { get; set; }
        public string AcctDtn { get; set; }
        public string DprTypID { get; set; }
        public Nullable<int> UseLife { get; set; }
        public int LogInstanc { get; set; }
        public Nullable<int> SnapshotId { get; set; }
    }
}
