//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AADT
    {
        public string Code { get; set; }
        public string Descr { get; set; }
        public string BalanceAct { get; set; }
        public string ClrAcqAct { get; set; }
        public string RevResvAct { get; set; }
        public string OrdDprAct { get; set; }
        public string OrdDprAcc { get; set; }
        public string UnpDprAct { get; set; }
        public string UnpDprAcc { get; set; }
        public string SpDprAct { get; set; }
        public string SpDprAcc { get; set; }
        public string SaRevNAct { get; set; }
        public string ReExpNAct { get; set; }
        public string ReRevNAct { get; set; }
        public string ReNBVeAct { get; set; }
        public string ReNBVrAct { get; set; }
        public string ClrDscAct { get; set; }
        public string RevReAct { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public int LogInstanc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ClearAccRe { get; set; }
        public string RevResvClr { get; set; }
        public Nullable<int> SnapshotId { get; set; }
    }
}
