//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACPN
    {
        public int CpnNo { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string TargetGrp { get; set; }
        public Nullable<int> Owner { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Remarks { get; set; }
        public string WizardGen { get; set; }
        public byte[] Template { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public string Attachment { get; set; }
        public int LogIns { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DataSource { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
        public string Url { get; set; }
        public string TmplPath { get; set; }
        public string TargetType { get; set; }
        public string ExeOption { get; set; }
        public string Executed { get; set; }
        public string VersionNum { get; set; }
    }
}
