//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACPR
    {
        public int CntctCode { get; set; }
        public string CardCode { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Address { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Cellolar { get; set; }
        public string Fax { get; set; }
        public string E_MailL { get; set; }
        public string Pager { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string Password { get; set; }
        public int LogInstanc { get; set; }
        public string ObjType { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string Profession { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> updateTime { get; set; }
        public string Title { get; set; }
        public string BirthCity { get; set; }
        public string Active { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string BirthState { get; set; }
        public string ResidCity { get; set; }
        public string ResidCntry { get; set; }
        public string ResidState { get; set; }
        public string NFeRcpn { get; set; }
        public string EmlGrpCode { get; set; }
        public string BlockComm { get; set; }
        public string FiscalCode { get; set; }
        public string CtyPrvsYr { get; set; }
        public string SttPrvsYr { get; set; }
        public string CtyCdPrvsY { get; set; }
        public string CtyCurYr { get; set; }
        public string SttCurYr { get; set; }
        public string CtyCdCurYr { get; set; }
        public string NotResdSch { get; set; }
        public string CtyFsnCode { get; set; }
        public string NaturalPer { get; set; }
        public string DPPStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public string EncryptIV { get; set; }
        public short U_conforma_factura { get; set; }
        public short U_conforma_remision { get; set; }
        public string U_club_social { get; set; }
        public string U_estado_civil { get; set; }
        public string U_propietario { get; set; }
        public string U_compra { get; set; }
        public string U_pagos { get; set; }
        public string U_tecnico { get; set; }
        public string U_nacionalidad { get; set; }
        public string U_pasatiempo { get; set; }
        public string U_zoho_id { get; set; }
        public Nullable<System.DateTime> U_fecha_cumple { get; set; }
        public string U_factura_electronica { get; set; }
    }
}
