//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR7
    {
        public string CardCode { get; set; }
        public string Address { get; set; }
        public string TaxId0 { get; set; }
        public string TaxId1 { get; set; }
        public string TaxId2 { get; set; }
        public string TaxId3 { get; set; }
        public string TaxId4 { get; set; }
        public string TaxId5 { get; set; }
        public string TaxId6 { get; set; }
        public string TaxId7 { get; set; }
        public string TaxId8 { get; set; }
        public string TaxId9 { get; set; }
        public Nullable<int> CNAEId { get; set; }
        public string TaxId10 { get; set; }
        public string TaxId11 { get; set; }
        public string AddrType { get; set; }
        public string ECCNo { get; set; }
        public string CERegNo { get; set; }
        public string CERange { get; set; }
        public string CEDivis { get; set; }
        public string CEComRate { get; set; }
        public int LogInstanc { get; set; }
        public Nullable<System.DateTime> SefazDate { get; set; }
        public string TaxId12 { get; set; }
        public string TaxId13 { get; set; }
    }
}
