//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADG1
    {
        public int AbsEntry { get; set; }
        public string ObjType { get; set; }
        public string ObjKey { get; set; }
        public string DiscType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PayFor { get; set; }
        public Nullable<decimal> ForFree { get; set; }
        public Nullable<decimal> UpTo { get; set; }
        public int LogInstanc { get; set; }
    }
}
