//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM2
    {
        public int Code { get; set; }
        public string TaxAuCod { get; set; }
        public string KeyEcoAct { get; set; }
        public string TaxPayType { get; set; }
        public string TaxLegForm { get; set; }
        public string RegName { get; set; }
        public string RegNameExt { get; set; }
        public string SoleFName { get; set; }
        public string SoleSName { get; set; }
        public string SoleTitle { get; set; }
        public string CityTown { get; set; }
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Street { get; set; }
        public string StreetNum { get; set; }
        public Nullable<int> BuildinNum { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public string RepType { get; set; }
        public string RepCode { get; set; }
        public string RepFName { get; set; }
        public string RepSName { get; set; }
        public string CompName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string TaxACNum { get; set; }
        public string LegEntitID { get; set; }
        public string AuthFName { get; set; }
        public string AuthLName { get; set; }
        public string AuthRelat { get; set; }
        public string AuthType { get; set; }
        public string TaxPayAttr { get; set; }
        public string Classifier { get; set; }
        public string DeprMethod { get; set; }
        public string SubmitPlac { get; set; }
        public string BgtClass { get; set; }
        public string SubjOfRuF { get; set; }
        public string AuthFathrN { get; set; }
        public string BgtCleVAT { get; set; }
        public string RepTitle { get; set; }
        public string TaxRegime { get; set; }
        public Nullable<System.DateTime> SoleBDate { get; set; }
        public string SoleGender { get; set; }
        public string SoleCity { get; set; }
        public string SoleDistri { get; set; }
        public string RepFisCode { get; set; }
        public string RepPosCode { get; set; }
        public string RepGender { get; set; }
        public string RepCity { get; set; }
        public string RepDistri { get; set; }
        public Nullable<System.DateTime> RepDate1 { get; set; }
        public Nullable<System.DateTime> RepDate2 { get; set; }
        public string RepPhone { get; set; }
        public string RepEmail { get; set; }
        public string Country { get; set; }
        public string District { get; set; }
        public string RegDistri { get; set; }
        public Nullable<decimal> RegSCAmnt { get; set; }
        public string RegSHolder { get; set; }
        public string RegLiquida { get; set; }
        public string RepAddID { get; set; }
        public string ActCode { get; set; }
        public string PosCode347 { get; set; }
        public string FiscalCode { get; set; }
        public string DataBoxID { get; set; }
        public Nullable<decimal> SmValLimit { get; set; }
        public string RepCEOName { get; set; }
        public string RepCEOFisC { get; set; }
    }
}
