//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEC1
    {
        public string Code { get; set; }
        public int LineNum { get; set; }
        public Nullable<short> StrIndex { get; set; }
        public int BPLId { get; set; }
        public string ParamType { get; set; }
        public string ParamVisib { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public short LogInstanc { get; set; }
        public string ParamPrms { get; set; }
        public Nullable<short> UIorder { get; set; }
        public Nullable<short> Type { get; set; }
    }
}
