//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEC6
    {
        public int Code { get; set; }
        public string GenType { get; set; }
        public Nullable<int> MapID { get; set; }
        public Nullable<int> MapID_WS { get; set; }
        public string TestMode { get; set; }
        public short LogInstanc { get; set; }
        public string ParamLogic { get; set; }
        public string ParamStr { get; set; }
        public string ParamLText { get; set; }
        public string ActStatus { get; set; }
        public Nullable<int> ParamUqc { get; set; }
        public Nullable<int> ParamInt { get; set; }
        public string ParamPAC { get; set; }
        public string ParamTgl { get; set; }
        public string ParamMon { get; set; }
        public string ParamLink { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Source { get; set; }
        public string ReportID { get; set; }
        public string AssignedID { get; set; }
        public string Confirm { get; set; }
    }
}
