//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHE7
    {
        public int empID { get; set; }
        public short line { get; set; }
        public string ConName { get; set; }
        public string PmntNotes { get; set; }
        public Nullable<decimal> AN { get; set; }
        public Nullable<decimal> AG { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string BankAcct { get; set; }
        public int LogInstanc { get; set; }
        public string ANCurrency { get; set; }
        public string AGCurrency { get; set; }
        public string Sequence { get; set; }
        public string EnBnkAcct { get; set; }
        public string EncryptIV { get; set; }
    }
}
