//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AINC
    {
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public int Series { get; set; }
        public Nullable<System.DateTime> CountDate { get; set; }
        public Nullable<int> Time { get; set; }
        public string CountType { get; set; }
        public Nullable<int> Taker1Type { get; set; }
        public Nullable<int> Taker1Id { get; set; }
        public Nullable<int> Taker2Type { get; set; }
        public Nullable<int> Taker2Id { get; set; }
        public string Status { get; set; }
        public string Ref2 { get; set; }
        public string Remarks { get; set; }
        public int LogIns { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ObjType { get; set; }
        public string WddStatus { get; set; }
        public Nullable<int> DraftKey { get; set; }
        public string Printed { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BPLName { get; set; }
        public Nullable<int> TeamCount { get; set; }
        public Nullable<int> IndvCount { get; set; }
        public Nullable<decimal> DiffQty { get; set; }
        public Nullable<decimal> DiffPercen { get; set; }
        public Nullable<int> UpdateTS { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public string PIndicator { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string VersionNum { get; set; }
        public string DataSource { get; set; }
    }
}
