//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIT11
    {
        public string ItemCode { get; set; }
        public string PeriodCat { get; set; }
        public string DprArea { get; set; }
        public int VisOrder { get; set; }
        public string DprSt { get; set; }
        public Nullable<decimal> factor { get; set; }
        public int LogInstanc { get; set; }
        public Nullable<int> ActualUnit { get; set; }
    }
}
