//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIT8
    {
        public string ItemCode { get; set; }
        public string PeriodCat { get; set; }
        public string DprArea { get; set; }
        public Nullable<decimal> APC { get; set; }
        public Nullable<decimal> APCHist { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> OrDpAcc { get; set; }
        public Nullable<decimal> UnDpAcc { get; set; }
        public string SpDpKey1 { get; set; }
        public Nullable<decimal> SpDpAcc1 { get; set; }
        public string SpDpKey2 { get; set; }
        public Nullable<decimal> SpDpAcc2 { get; set; }
        public string SpDpKey3 { get; set; }
        public Nullable<decimal> SpDpAcc3 { get; set; }
        public int LogInstanc { get; set; }
        public string ObjType { get; set; }
        public Nullable<decimal> SalvageVal { get; set; }
        public Nullable<decimal> OrDpAcc1 { get; set; }
        public Nullable<decimal> WriteUpAcc { get; set; }
        public string IsMaSalVal { get; set; }
        public Nullable<decimal> AppreAcc { get; set; }
    }
}
