//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AKL1
    {
        public int AbsEntry { get; set; }
        public int PickEntry { get; set; }
        public Nullable<int> OrderEntry { get; set; }
        public Nullable<int> OrderLine { get; set; }
        public Nullable<decimal> PickQtty { get; set; }
        public string PickStatus { get; set; }
        public Nullable<decimal> RelQtty { get; set; }
        public int LogInsac { get; set; }
        public Nullable<decimal> PrevReleas { get; set; }
        public Nullable<int> BaseObject { get; set; }
        public string U_UBIC_ITEM { get; set; }
    }
}
