//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMD1
    {
        public int LineNum { get; set; }
        public int PmnNum { get; set; }
        public int PmnInvID { get; set; }
        public Nullable<System.DateTime> PmnDate { get; set; }
        public string CardCode { get; set; }
        public string InvType { get; set; }
        public Nullable<int> InvEntry { get; set; }
        public Nullable<short> InstId { get; set; }
        public Nullable<int> InvTransID { get; set; }
        public string FCCurrency { get; set; }
        public Nullable<decimal> InvRate { get; set; }
        public Nullable<decimal> PmnRate { get; set; }
        public string Approved { get; set; }
        public Nullable<decimal> AmountDiff { get; set; }
        public Nullable<decimal> TaxAmtDiff { get; set; }
        public string TMP_JE { get; set; }
    }
}
