//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMG
    {
        public int AbsEntry { get; set; }
        public Nullable<int> OWNER { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<decimal> FINISHED { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Series { get; set; }
        public string TYP { get; set; }
        public string CARDCODE { get; set; }
        public string CARDNAME { get; set; }
        public Nullable<int> CONTACT { get; set; }
        public Nullable<int> TERRITORY { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
        public string WithPhases { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<System.DateTime> CLOSING { get; set; }
        public string FIPROJECT { get; set; }
        public string RISK { get; set; }
        public Nullable<int> INDUSTRY { get; set; }
        public string REASON { get; set; }
        public string Free_Text { get; set; }
        public Nullable<int> BPLid { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public string Attachment { get; set; }
        public int LogInstanc { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateTS { get; set; }
        public string DPPStatus { get; set; }
        public string EncryptIV { get; set; }
    }
}
