//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARC4
    {
        public int DocNum { get; set; }
        public int LineId { get; set; }
        public string AcctCode { get; set; }
        public Nullable<decimal> SumApplied { get; set; }
        public Nullable<decimal> AppliedFC { get; set; }
        public Nullable<decimal> AppliedSys { get; set; }
        public string Descrip { get; set; }
        public string VatGroup { get; set; }
        public Nullable<decimal> VatPrcnt { get; set; }
        public string AcctName { get; set; }
        public string ObjType { get; set; }
        public int LogInstanc { get; set; }
        public string OcrCode { get; set; }
        public string Project { get; set; }
        public Nullable<decimal> GrossAmnt { get; set; }
        public Nullable<decimal> GrssAmntFC { get; set; }
        public Nullable<decimal> GrssAmntSC { get; set; }
        public string AmntBase { get; set; }
        public Nullable<decimal> VatAmnt { get; set; }
        public Nullable<decimal> VatAmntFC { get; set; }
        public Nullable<decimal> VatAmntSC { get; set; }
        public string UserChaVat { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public Nullable<int> Section { get; set; }
        public string AsseType { get; set; }
        public Nullable<int> LocCode { get; set; }
        public Nullable<int> MatType { get; set; }
        public Nullable<decimal> EquVatPer { get; set; }
        public Nullable<decimal> EquVatSum { get; set; }
        public Nullable<decimal> EquVatSumF { get; set; }
        public Nullable<decimal> EquVatSumS { get; set; }
        public string EncryptIV { get; set; }
        public string U_NumeFact { get; set; }
        public Nullable<decimal> U_ImpoFact { get; set; }
        public string U_NroRet { get; set; }
        public Nullable<decimal> U_PorcRetencion { get; set; }
        public string U_CodProveedor { get; set; }
        public Nullable<System.DateTime> U_fecha { get; set; }
    }
}
