//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARC7
    {
        public int DocNum { get; set; }
        public int LineSeq { get; set; }
        public Nullable<int> InvoiceSeq { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> Inv4Seq { get; set; }
        public Nullable<decimal> TaxSum { get; set; }
        public Nullable<decimal> TaxSumFrgn { get; set; }
        public Nullable<decimal> TaxSumSys { get; set; }
        public Nullable<decimal> BaseSum { get; set; }
        public Nullable<decimal> BaseSumFrg { get; set; }
        public Nullable<decimal> BaseSumSys { get; set; }
        public string ObjectType { get; set; }
        public int LogInstanc { get; set; }
        public string EncryptIV { get; set; }
    }
}
