//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSC
    {
        public string ResCode { get; set; }
        public string VisResCode { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> Number { get; set; }
        public string CodeBars { get; set; }
        public string ResName { get; set; }
        public string FrgnName { get; set; }
        public string ResType { get; set; }
        public Nullable<short> ResGrpCod { get; set; }
        public string UnitOfMsr { get; set; }
        public string PrchseRes { get; set; }
        public string SellRes { get; set; }
        public string ProdRes { get; set; }
        public string CardCode { get; set; }
        public string NoDiscount { get; set; }
        public string IssueMthd { get; set; }
        public Nullable<decimal> StdCost1 { get; set; }
        public Nullable<decimal> StdCost2 { get; set; }
        public Nullable<decimal> StdCost3 { get; set; }
        public Nullable<decimal> StdCost4 { get; set; }
        public Nullable<decimal> StdCost5 { get; set; }
        public Nullable<decimal> StdCost6 { get; set; }
        public Nullable<decimal> StdCost7 { get; set; }
        public Nullable<decimal> StdCost8 { get; set; }
        public Nullable<decimal> StdCost9 { get; set; }
        public Nullable<decimal> StdCost10 { get; set; }
        public string validFor { get; set; }
        public Nullable<System.DateTime> validFrom { get; set; }
        public Nullable<System.DateTime> validTo { get; set; }
        public string frozenFor { get; set; }
        public Nullable<System.DateTime> frozenFrom { get; set; }
        public Nullable<System.DateTime> frozenTo { get; set; }
        public string DfltWH { get; set; }
        public Nullable<int> QueryGroup { get; set; }
        public string PicturName { get; set; }
        public string UserText { get; set; }
        public string QryGroup1 { get; set; }
        public string QryGroup2 { get; set; }
        public string QryGroup3 { get; set; }
        public string QryGroup4 { get; set; }
        public string QryGroup5 { get; set; }
        public string QryGroup6 { get; set; }
        public string QryGroup7 { get; set; }
        public string QryGroup8 { get; set; }
        public string QryGroup9 { get; set; }
        public string QryGroup10 { get; set; }
        public string QryGroup11 { get; set; }
        public string QryGroup12 { get; set; }
        public string QryGroup13 { get; set; }
        public string QryGroup14 { get; set; }
        public string QryGroup15 { get; set; }
        public string QryGroup16 { get; set; }
        public string QryGroup17 { get; set; }
        public string QryGroup18 { get; set; }
        public string QryGroup19 { get; set; }
        public string QryGroup20 { get; set; }
        public string QryGroup21 { get; set; }
        public string QryGroup22 { get; set; }
        public string QryGroup23 { get; set; }
        public string QryGroup24 { get; set; }
        public string QryGroup25 { get; set; }
        public string QryGroup26 { get; set; }
        public string QryGroup27 { get; set; }
        public string QryGroup28 { get; set; }
        public string QryGroup29 { get; set; }
        public string QryGroup30 { get; set; }
        public string QryGroup31 { get; set; }
        public string QryGroup32 { get; set; }
        public string QryGroup33 { get; set; }
        public string QryGroup34 { get; set; }
        public string QryGroup35 { get; set; }
        public string QryGroup36 { get; set; }
        public string QryGroup37 { get; set; }
        public string QryGroup38 { get; set; }
        public string QryGroup39 { get; set; }
        public string QryGroup40 { get; set; }
        public string QryGroup41 { get; set; }
        public string QryGroup42 { get; set; }
        public string QryGroup43 { get; set; }
        public string QryGroup44 { get; set; }
        public string QryGroup45 { get; set; }
        public string QryGroup46 { get; set; }
        public string QryGroup47 { get; set; }
        public string QryGroup48 { get; set; }
        public string QryGroup49 { get; set; }
        public string QryGroup50 { get; set; }
        public string QryGroup51 { get; set; }
        public string QryGroup52 { get; set; }
        public string QryGroup53 { get; set; }
        public string QryGroup54 { get; set; }
        public string QryGroup55 { get; set; }
        public string QryGroup56 { get; set; }
        public string QryGroup57 { get; set; }
        public string QryGroup58 { get; set; }
        public string QryGroup59 { get; set; }
        public string QryGroup60 { get; set; }
        public string QryGroup61 { get; set; }
        public string QryGroup62 { get; set; }
        public string QryGroup63 { get; set; }
        public string QryGroup64 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DataSource { get; set; }
        public string ValidComm { get; set; }
        public string FrozenComm { get; set; }
        public int LogInstanc { get; set; }
        public string ObjType { get; set; }
        public string Deleted { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public Nullable<decimal> LastPurPrc { get; set; }
        public string LastPurCur { get; set; }
        public Nullable<System.DateTime> LastPurDat { get; set; }
        public Nullable<decimal> LstEvlPric { get; set; }
        public Nullable<System.DateTime> LstEvlDate { get; set; }
        public Nullable<int> NumResUnit { get; set; }
        public Nullable<int> TimeResUn { get; set; }
        public string ResAlloc { get; set; }
        public string LinkItm { get; set; }
        public string RelCap1 { get; set; }
        public string RelCap2 { get; set; }
        public string RelCap3 { get; set; }
        public string RelCap4 { get; set; }
        public Nullable<short> UserSign { get; set; }
    }
}
