//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASC4
    {
        public int SrcvCallID { get; set; }
        public short Line { get; set; }
        public string PartType { get; set; }
        public int DocAbs { get; set; }
        public string Object { get; set; }
        public Nullable<System.DateTime> DocPstDate { get; set; }
        public string ObjectType { get; set; }
        public int LogInstanc { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DocNumber { get; set; }
        public string Transfered { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string StckTrnDir { get; set; }
        public Nullable<short> Instance { get; set; }
    }
}
