//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASC6
    {
        public int SrcvCallID { get; set; }
        public short Line { get; set; }
        public Nullable<int> Technician { get; set; }
        public Nullable<short> HandledBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<short> Location { get; set; }
        public string AddressId { get; set; }
        public string Address { get; set; }
        public string Reminder { get; set; }
        public Nullable<decimal> RemQty { get; set; }
        public string DisplInCal { get; set; }
        public string Unsched { get; set; }
        public string DurType { get; set; }
        public string RemType { get; set; }
        public int LogInstanc { get; set; }
        public Nullable<System.DateTime> RemDate { get; set; }
        public string RemSent { get; set; }
        public Nullable<short> RemTime { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Room { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string AddrType { get; set; }
        public string StreetNo { get; set; }
        public string ZipCode { get; set; }
        public string Block { get; set; }
        public string County { get; set; }
        public string TaxOffice { get; set; }
        public string GlblLocNum { get; set; }
        public Nullable<decimal> ActualDur { get; set; }
        public string ActDurType { get; set; }
        public string Close { get; set; }
        public string Remark { get; set; }
        public string AddrTypeBS { get; set; }
        public string SignName { get; set; }
        public string SaleOrders { get; set; }
        public Nullable<System.DateTime> ChkInDate { get; set; }
        public Nullable<int> ChkInTime { get; set; }
        public string ChkInLoc { get; set; }
        public string ChkLontitu { get; set; }
        public string ChkLatitu { get; set; }
        public Nullable<System.DateTime> ChkOutDate { get; set; }
        public Nullable<int> ChkOutTime { get; set; }
        public byte[] SignData { get; set; }
        public string EncryptIV { get; set; }
    }
}
