//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATX2
    {
        public int BaseEntry { get; set; }
        public int LineNum { get; set; }
        public int OpCode { get; set; }
        public int ObjType { get; set; }
        public int LogInstanc { get; set; }
    }
}
