//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUG1
    {
        public int UgpEntry { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public Nullable<decimal> AltQty { get; set; }
        public Nullable<decimal> BaseQty { get; set; }
        public int LogInstanc { get; set; }
        public int LineNum { get; set; }
        public Nullable<short> WghtFactor { get; set; }
        public Nullable<int> UdfFactor { get; set; }
    }
}
