//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWD2
    {
        public int AbsEntry { get; set; }
        public Nullable<System.DateTime> EfctFrom { get; set; }
        public Nullable<decimal> ValueFrom { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string WTCur { get; set; }
        public int LogInstanc { get; set; }
        public int LineNum { get; set; }
        public int SeqNum { get; set; }
    }
}
