//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWD4
    {
        public int AbsEntry { get; set; }
        public int LineId { get; set; }
        public string WTCode { get; set; }
        public string ItemCode { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string DataSource { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int LogInstanc { get; set; }
    }
}
