//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWO5
    {
        public int DocEntry { get; set; }
        public string ObjType { get; set; }
        public int LogInstanc { get; set; }
        public int LineNum { get; set; }
        public Nullable<int> RefDocEntr { get; set; }
        public Nullable<int> RefDocNum { get; set; }
        public string ExtDocNum { get; set; }
        public string RefObjType { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Remark { get; set; }
    }
}
