//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWT
    {
        public int Id { get; set; }
        public string Owner { get; set; }
        public string OutputPar { get; set; }
        public string EndTime { get; set; }
        public string StartTime { get; set; }
        public Nullable<int> ProcDefId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ExeId { get; set; }
        public Nullable<int> ProcInsId { get; set; }
        public string Desc { get; set; }
        public string InputPar { get; set; }
        public string DelReason { get; set; }
        public string Assignee { get; set; }
        public int LogInst { get; set; }
        public string LastUpdate { get; set; }
        public string Key { get; set; }
        public Nullable<int> B1Task { get; set; }
    }
}
