//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BGT1
    {
        public int BudgId { get; set; }
        public int Line_ID { get; set; }
        public Nullable<decimal> DebLTotal { get; set; }
        public Nullable<decimal> CredLTotal { get; set; }
        public Nullable<decimal> DebSTotal { get; set; }
        public Nullable<decimal> CredSTotal { get; set; }
        public Nullable<decimal> DebRLTotal { get; set; }
        public Nullable<decimal> CrdRLTotal { get; set; }
        public Nullable<decimal> DebRSTotal { get; set; }
        public Nullable<decimal> CrdRSTotal { get; set; }
        public Nullable<decimal> FtrIDRLSum { get; set; }
        public Nullable<decimal> FtrIDRSSum { get; set; }
        public Nullable<decimal> FtrICRLSum { get; set; }
        public Nullable<decimal> FtrICRSSum { get; set; }
        public Nullable<decimal> FtrODRLSum { get; set; }
        public Nullable<decimal> FtrODRSSum { get; set; }
        public Nullable<decimal> FtrOCRLSum { get; set; }
        public Nullable<decimal> FtrOCRSSum { get; set; }
        public Nullable<decimal> MonthPrcnt { get; set; }
        public string LineMemo { get; set; }
        public Nullable<int> Instance { get; set; }
        public string AcctCode { get; set; }
        public Nullable<short> UserSign { get; set; }
    }
}
