//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNK1
    {
        public int IdNumber { get; set; }
        public int BSLine { get; set; }
        public short ListLineID { get; set; }
        public string DocID { get; set; }
        public Nullable<decimal> AmntLC { get; set; }
        public Nullable<decimal> AmnFC { get; set; }
        public string IsDebit { get; set; }
    }
}
