//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOE1
    {
        public int BoeKey { get; set; }
        public int LineId { get; set; }
        public string LineDitail { get; set; }
        public Nullable<decimal> LineMoney { get; set; }
        public string LineCurr { get; set; }
        public string LineAcct { get; set; }
        public string Line_A_C { get; set; }
        public string Code { get; set; }
        public string CredAcct { get; set; }
        public Nullable<decimal> TotalLine { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<int> UserSign { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string EncryptIV { get; set; }
        public string U_sucursal { get; set; }
        public Nullable<System.DateTime> U_fecha_recaudacion { get; set; }
    }
}
