//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOX2
    {
        public string BoxCode { get; set; }
        public string ReportType { get; set; }
        public string Account { get; set; }
        public Nullable<int> SeqNum { get; set; }
        public Nullable<System.DateTime> EffecDate { get; set; }
        public int BosCode { get; set; }
    }
}
