//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPL2
    {
        public int BPLId { get; set; }
        public int TributID { get; set; }
        public Nullable<int> TributType { get; set; }
        public Nullable<System.DateTime> TTStartDat { get; set; }
        public Nullable<System.DateTime> TTEndDate { get; set; }
        public Nullable<int> TribRegCod { get; set; }
        public Nullable<System.DateTime> TRCStartD { get; set; }
        public Nullable<System.DateTime> TRCEndDate { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
    }
}
