//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ACCESO_DIRECTO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int U_id_usuario { get; set; }
        public string U_id_formulario { get; set; }
        public string U_id_teclas { get; set; }
    }
}
