//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ARTICULOS_ESPECIFIC
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_item1 { get; set; }
        public Nullable<decimal> U_maximo1 { get; set; }
        public string U_item2 { get; set; }
        public Nullable<decimal> U_maximo2 { get; set; }
        public string U_item3 { get; set; }
        public Nullable<decimal> U_maximo3 { get; set; }
        public string U_item4 { get; set; }
        public Nullable<decimal> U_maximo4 { get; set; }
        public string U_item5 { get; set; }
        public Nullable<decimal> U_maximo5 { get; set; }
        public string U_item6 { get; set; }
        public Nullable<decimal> U_maximo6 { get; set; }
        public string U_item7 { get; set; }
        public Nullable<decimal> U_maximo7 { get; set; }
        public string U_item8 { get; set; }
        public Nullable<decimal> U_maximo8 { get; set; }
        public string U_item9 { get; set; }
        public Nullable<decimal> U_maximo9 { get; set; }
        public string U_item10 { get; set; }
        public Nullable<decimal> U_maximo10 { get; set; }
    }
}
