//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOQUOT
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> U_MyQ { get; set; }
        public Nullable<int> U_Status { get; set; }
        public Nullable<System.DateTime> U_FromD { get; set; }
        public Nullable<System.DateTime> U_ToD { get; set; }
        public Nullable<int> U_LastDs { get; set; }
    }
}
