//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOEXCEL
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_FollowUp { get; set; }
        public Nullable<int> U_Activity { get; set; }
        public Nullable<int> U_FlwTime { get; set; }
        public Nullable<int> U_FlwUnit { get; set; }
        public Nullable<int> U_FlwDur { get; set; }
        public Nullable<int> U_FlwDurUn { get; set; }
        public string U_Reminder { get; set; }
        public Nullable<int> U_RemTime { get; set; }
        public Nullable<int> U_RemUnit { get; set; }
    }
}
