//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOOSTP
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_TplName { get; set; }
        public Nullable<int> U_Language { get; set; }
        public string U_CPData { get; set; }
        public Nullable<int> U_CatID { get; set; }
        public string U_LFileXls { get; set; }
        public string U_LFileTxt { get; set; }
        public string U_CrtUser { get; set; }
        public Nullable<System.DateTime> U_CrtTime { get; set; }
        public string U_ChgUser { get; set; }
        public Nullable<System.DateTime> U_ChgTime { get; set; }
        public string U_Default { get; set; }
        public string U_Version { get; set; }
        public string U_Host { get; set; }
    }
}
