//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOOADM
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_LFPath { get; set; }
        public string U_CrtUser { get; set; }
        public Nullable<System.DateTime> U_CrtTime { get; set; }
        public string U_ChgUser { get; set; }
        public Nullable<System.DateTime> U_ChgTime { get; set; }
        public string U_LFSPath { get; set; }
        public string U_Version { get; set; }
        public string U_Host { get; set; }
    }
}
