//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOSYNCLOG
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_UserID { get; set; }
        public string U_Start { get; set; }
        public string U_End { get; set; }
        public Nullable<int> U_Status { get; set; }
        public string U_SyncCa { get; set; }
        public string U_SyncCo { get; set; }
        public string U_SyncTa { get; set; }
    }
}
