//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOSTP1
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> U_Sequence { get; set; }
        public string U_TplCode { get; set; }
        public Nullable<int> U_QueryID { get; set; }
        public Nullable<int> U_NumRec { get; set; }
        public string U_ReadLast { get; set; }
        public string U_RgData { get; set; }
        public Nullable<int> U_QCatID { get; set; }
    }
}
