//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CIM
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> U_fecha_recepcion { get; set; }
        public Nullable<System.DateTime> U_fecha_documento { get; set; }
        public Nullable<System.DateTime> U_fecha_inicio { get; set; }
        public Nullable<System.DateTime> U_fecha_fin { get; set; }
        public string U_nro_importacion { get; set; }
        public string U_almacen { get; set; }
        public Nullable<int> U_usersign { get; set; }
        public Nullable<int> U_solicitado_por { get; set; }
        public string U_comentarios { get; set; }
        public Nullable<int> U_prioridad { get; set; }
        public short U_notificar { get; set; }
        public short U_wf_precio_entrega { get; set; }
        public short U_wf_notificacion { get; set; }
        public Nullable<short> U_compras_locales { get; set; }
        public string U_folio_pre { get; set; }
        public Nullable<int> U_folio_num { get; set; }
        public string U_control_por { get; set; }
        public string U_recibido_por { get; set; }
        public Nullable<short> U_origen { get; set; }
        public string U_referencia { get; set; }
        public Nullable<System.DateTime> U_fecha_estimada_r { get; set; }
        public Nullable<System.DateTime> U_fecha_estimada_r_h { get; set; }
        public string U_adjunto1 { get; set; }
        public string U_adjunto2 { get; set; }
        public string U_adjunto3 { get; set; }
    }
}
