//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CIM_DETALLE
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public string U_itemcode { get; set; }
        public string U_itemname { get; set; }
        public string U_status { get; set; }
        public Nullable<short> U_tipo_documento { get; set; }
        public Nullable<int> U_docentry { get; set; }
        public Nullable<int> U_docnum { get; set; }
        public string U_comentarios { get; set; }
        public Nullable<decimal> U_cantidad { get; set; }
        public decimal U_conforme { get; set; }
        public decimal U_recuperable { get; set; }
        public decimal U_no_recuperable { get; set; }
        public decimal U_faltante { get; set; }
        public decimal U_sobrante { get; set; }
        public string U_itemcode_sob { get; set; }
        public string U_itemname_sob { get; set; }
        public Nullable<System.DateTime> U_inicio_control { get; set; }
        public Nullable<System.DateTime> U_fin_control { get; set; }
        public short U_notificar { get; set; }
        public short U_traslado_c { get; set; }
        public short U_traslado_r { get; set; }
        public short U_traslado_n { get; set; }
        public short U_ajuste_f { get; set; }
        public short U_ajuste_s { get; set; }
        public short U_wf_precio_venta { get; set; }
        public Nullable<short> U_prioridad { get; set; }
        public Nullable<int> U_linebase { get; set; }
        public Nullable<short> U_enviarnoti { get; set; }
        public short U_wf_ubicacion { get; set; }
        public Nullable<System.DateTime> U_wf_hora_confirma { get; set; }
        public short U_wf_notificacion { get; set; }
    }
}
