//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CONTROL_TAREA_AUT
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> U_fecha_verif { get; set; }
        public Nullable<short> U_tipo { get; set; }
    }
}
