//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CONFIGPY
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_ESTA { get; set; }
        public string U_PEMI { get; set; }
        public string U_SUC { get; set; }
        public int U_timbrado { get; set; }
        public string U_TipoDoc { get; set; }
        public string U_TimbradoNro { get; set; }
        public Nullable<int> U_NroDocDesde { get; set; }
        public Nullable<int> U_NroDocHasta { get; set; }
        public Nullable<System.DateTime> U_FechaVto { get; set; }
    }
}
