//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CONT_ENT_SAL_DOC
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_ControlId { get; set; }
        public Nullable<int> U_DocType { get; set; }
        public Nullable<int> U_DocEntry { get; set; }
        public Nullable<int> U_DocNum { get; set; }
        public Nullable<int> U_Orden { get; set; }
        public Nullable<int> U_LineIn { get; set; }
        public Nullable<int> U_LineOut { get; set; }
    }
}
