//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FAB_PRIORIDAD
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<short> U_Firmcode { get; set; }
        public string U_Firmname { get; set; }
        public string U_Priority { get; set; }
    }
}
