//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FONDO_FIJO_DET
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public string U_nro_factura { get; set; }
        public string U_acreedor { get; set; }
        public string U_autorizante { get; set; }
        public Nullable<int> U_total { get; set; }
        public string U_moneda { get; set; }
        public string U_concepto { get; set; }
    }
}
