//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GRUPO_ECONOMICO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_clasificacion { get; set; }
        public Nullable<decimal> U_promedio { get; set; }
        public Nullable<decimal> U_margen_bruto { get; set; }
    }
}
