//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GT_CONF_TAREA
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<System.DateTime> U_fecha { get; set; }
        public string U_confirmado { get; set; }
        public string U_comentario { get; set; }
    }
}
