//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GT_SUB_TIPO
    {
        public string Code { get; set; }
        public int LineId { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public string U_name { get; set; }
        public Nullable<short> U_critico { get; set; }
        public Nullable<short> U_con_cantidad { get; set; }
        public Nullable<short> U_tarea_aut { get; set; }
        public Nullable<int> U_stock { get; set; }
        public Nullable<short> U_tarea_semanal { get; set; }
        public Nullable<short> U_tarea_quincenal { get; set; }
        public Nullable<short> U_tarea_mensual { get; set; }
    }
}
