//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_IMP_IMP_ARAN
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> U_porc_aran { get; set; }
        public Nullable<decimal> U_imp_a_distr { get; set; }
        public string U_importacion { get; set; }
        public Nullable<decimal> U_imp_base_imponible { get; set; }
    }
}
