//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_IND_PROCESO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> U_obj_minimo { get; set; }
        public string U_unidad_medida { get; set; }
        public string U_nombre { get; set; }
        public string U_formula { get; set; }
    }
}
