//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_IND_INDICADORES
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int DocEntry { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string U_proceso { get; set; }
        public string U_metrica { get; set; }
        public Nullable<int> U_obj_minimo { get; set; }
        public Nullable<int> U_obj_logrado { get; set; }
        public Nullable<short> U_mes { get; set; }
        public Nullable<short> U_anho { get; set; }
        public string U_responsable { get; set; }
        public Nullable<short> U_frecuencia { get; set; }
        public string U_area { get; set; }
        public string U_unidad_medida { get; set; }
        public Nullable<short> U_usersign2 { get; set; }
        public short U_aplica { get; set; }
        public string U_comentario { get; set; }
        public string U_formula { get; set; }
    }
}
