//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MARCA_COMISION
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_categoria { get; set; }
        public Nullable<decimal> U_porcentaje { get; set; }
        public Nullable<System.DateTime> U_periodo { get; set; }
        public Nullable<System.DateTime> U_fecha_creado { get; set; }
        public Nullable<System.DateTime> U_fecha_modificado { get; set; }
        public string U_usuario { get; set; }
        public Nullable<short> U_marca { get; set; }
        public decimal U_ponderacion { get; set; }
    }
}
