//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MARCA_SEGUIMIENTO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<short> U_controlar_exc { get; set; }
        public Nullable<short> U_dias_ideal { get; set; }
        public Nullable<short> U_marca { get; set; }
        public string U_proveedor { get; set; }
    }
}
