//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OBJETIVO_COBRO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public short U_year { get; set; }
        public short U_month { get; set; }
        public Nullable<decimal> U_obj { get; set; }
        public Nullable<decimal> U_cta_seleccionada { get; set; }
    }
}
