//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OBJETIVO_VENTA
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public short U_year { get; set; }
        public short U_Month { get; set; }
        public Nullable<short> U_slpcode { get; set; }
        public int U_obj { get; set; }
        public Nullable<short> U_dias { get; set; }
        public Nullable<decimal> U_salarioBase { get; set; }
        public Nullable<short> U_teamid { get; set; }
        public string U_unidad { get; set; }
        public Nullable<short> U_division { get; set; }
        public short U_dias_mayorista { get; set; }
        public decimal U_cobertura { get; set; }
    }
}
