//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OM_PRELIMINARES
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_detectado_por { get; set; }
        public Nullable<short> U_estado { get; set; }
        public Nullable<short> U_reg_nro { get; set; }
        public string U_equipo { get; set; }
        public Nullable<System.DateTime> U_detectado_el { get; set; }
        public string U_descripcion { get; set; }
        public string U_motivo { get; set; }
        public string U_comentarios { get; set; }
        public Nullable<System.DateTime> U_modificado_el { get; set; }
    }
}
