//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ORDEN_TRABAJO
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public string U_chapa { get; set; }
        public Nullable<int> U_kilometraje { get; set; }
        public Nullable<short> U_conductor { get; set; }
        public Nullable<short> U_camion { get; set; }
        public Nullable<short> U_moto { get; set; }
        public Nullable<short> U_5000 { get; set; }
        public Nullable<short> U_10000 { get; set; }
        public Nullable<short> U_20000 { get; set; }
        public Nullable<short> U_mensual { get; set; }
        public Nullable<int> U_usersign2 { get; set; }
        public Nullable<int> U_vehiculo { get; set; }
        public string U_taller { get; set; }
        public string U_factura_nro { get; set; }
        public Nullable<int> U_monto { get; set; }
        public Nullable<short> U_preventivo { get; set; }
        public Nullable<short> U_correctivo { get; set; }
        public string U_observacion { get; set; }
        public string U_realizado { get; set; }
    }
}
