//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PERMISOS_DEP_DET
    {
        public int DocEntry { get; set; }
        public int LineId { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public string U_OBJECT_TYPE { get; set; }
        public string U_SECTOR { get; set; }
        public string U_AUTORIZACION { get; set; }
        public string U_COD_DEPOSITO { get; set; }
        public string U_NOMBRE_DEPOSITO { get; set; }
        public string U_control_fecha { get; set; }
        public string U_TIPO_MOVI { get; set; }
    }
}
