//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PIC
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public Nullable<int> U_userSign2 { get; set; }
        public string U_caja { get; set; }
        public Nullable<int> U_nivel1 { get; set; }
        public Nullable<int> U_nivel2 { get; set; }
        public Nullable<int> U_nivel3 { get; set; }
        public Nullable<System.DateTime> U_fecha_nivel1 { get; set; }
        public Nullable<System.DateTime> U_fecha_nivel2 { get; set; }
        public Nullable<System.DateTime> U_fecha_nivel3 { get; set; }
        public string U_nro_bolsa { get; set; }
        public string U_nro_precinto { get; set; }
        public string U_nro_boleta { get; set; }
        public Nullable<decimal> U_banco { get; set; }
        public Nullable<decimal> U_redondeo { get; set; }
        public Nullable<decimal> U_no_pagado { get; set; }
        public Nullable<decimal> U_efectivo { get; set; }
        public Nullable<decimal> U_cheque { get; set; }
        public Nullable<decimal> U_tarjeta { get; set; }
        public Nullable<decimal> U_transferencia { get; set; }
        public Nullable<decimal> U_no_calculado { get; set; }
        public Nullable<decimal> U_total { get; set; }
        public Nullable<decimal> U_retencion { get; set; }
        public Nullable<decimal> U_canje { get; set; }
        public Nullable<decimal> U_anticipo { get; set; }
    }
}
