//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PROMOCIONES_DETALLE
    {
        public string Code { get; set; }
        public int LineId { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> U_grupo { get; set; }
        public string U_nombre { get; set; }
        public Nullable<decimal> U_descuento { get; set; }
        public string U_tipo { get; set; }
        public Nullable<decimal> U_cupon_extra { get; set; }
    }
}
