//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RECAUDACIONES
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public Nullable<int> U_usersign2 { get; set; }
        public string U_observacion { get; set; }
        public Nullable<int> U_usuario { get; set; }
        public Nullable<int> U_verificadopor { get; set; }
        public string U_caja { get; set; }
        public Nullable<int> U_monto_total { get; set; }
        public Nullable<int> U_monto_sap { get; set; }
        public Nullable<int> U_montoPesos_total { get; set; }
        public Nullable<int> U_montoPesos_sap { get; set; }
        public Nullable<int> U_montoReal_total { get; set; }
        public Nullable<int> U_montoReal_sap { get; set; }
        public Nullable<int> U_montoDolar_total { get; set; }
        public Nullable<int> U_montoDolar_sap { get; set; }
        public Nullable<int> U_montoEuro_total { get; set; }
        public Nullable<int> U_montoEuro_sap { get; set; }
        public Nullable<int> U_montoLibra_total { get; set; }
        public Nullable<int> U_montoLibra_sap { get; set; }
        public Nullable<int> U_nivel1 { get; set; }
        public Nullable<int> U_nivel2 { get; set; }
        public Nullable<int> U_nivel3 { get; set; }
        public Nullable<System.DateTime> U_fechaNivel1 { get; set; }
        public Nullable<System.DateTime> U_fechaNivel2 { get; set; }
        public Nullable<System.DateTime> U_fechaNivel3 { get; set; }
        public string U_nro_bolsa { get; set; }
        public string U_nro_precinto { get; set; }
        public string U_nro_boleta { get; set; }
    }
}
