//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VOUCHER
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public Nullable<int> U_nro_responsable { get; set; }
        public string U_nombre_responsable { get; set; }
        public Nullable<int> U_km { get; set; }
        public Nullable<int> U_cantidad { get; set; }
        public Nullable<int> U_precio { get; set; }
        public Nullable<int> U_total { get; set; }
        public Nullable<System.DateTime> U_fecha_voucher { get; set; }
        public Nullable<int> U_usersign2 { get; set; }
        public string U_nro_boleta { get; set; }
        public string U_nro_tarjeta { get; set; }
        public string U_periodo { get; set; }
        public Nullable<int> U_rendido { get; set; }
        public Nullable<short> U_vehiculo { get; set; }
        public string U_combustible { get; set; }
        public Nullable<decimal> U_combustible_costo { get; set; }
        public Nullable<System.DateTime> U_fecha_recepcion { get; set; }
        public Nullable<decimal> U_importe { get; set; }
    }
}
