//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCA1
    {
        public int AbsEntry { get; set; }
        public int LineNum { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> LogTime { get; set; }
        public string Action { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public Nullable<int> ErrorDet { get; set; }
        public string IDTable { get; set; }
        public string IDColumn { get; set; }
        public string IDAccount { get; set; }
        public string IDValue { get; set; }
        public string ValueOld { get; set; }
        public string ValueNew { get; set; }
    }
}
