//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC1
    {
        public string CdcCode { get; set; }
        public int LineId { get; set; }
        public Nullable<short> NumOfDays { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<short> Day { get; set; }
        public Nullable<short> Month { get; set; }
    }
}
