//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIVI
    {
        public int AbsEntry { get; set; }
        public string EnableRun { get; set; }
        public Nullable<System.DateTime> EnblRunDt { get; set; }
        public Nullable<int> MsgSource { get; set; }
        public string IsOILMUpd { get; set; }
        public Nullable<int> EnblDays { get; set; }
        public Nullable<int> LstChkMsg { get; set; }
        public Nullable<System.DateTime> LstMsgDate { get; set; }
        public Nullable<int> LstHndlMsg { get; set; }
        public string EnableUpd { get; set; }
        public string IgnPreUpd { get; set; }
        public string ForceRSP { get; set; }
        public Nullable<System.DateTime> ReorderFrm { get; set; }
        public Nullable<System.DateTime> ReorderTo { get; set; }
        public string InitMap { get; set; }
        public string InitStd { get; set; }
    }
}
