//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPL1
    {
        public int AbsEntry { get; set; }
        public int LogId { get; set; }
        public string ObjectID { get; set; }
        public string Instance { get; set; }
        public string ErrCode { get; set; }
        public string MessageId { get; set; }
        public string MessageDes { get; set; }
        public string InstName { get; set; }
    }
}
