//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPRF
    {
        public string FormID { get; set; }
        public string ItemID { get; set; }
        public string ColID { get; set; }
        public Nullable<int> Width { get; set; }
        public string VisInForm { get; set; }
        public Nullable<int> VisualIndx { get; set; }
        public string EditInForm { get; set; }
        public string VisInExpnd { get; set; }
        public Nullable<int> ExpandIndx { get; set; }
        public string EditInEXP { get; set; }
        public string Folded { get; set; }
        public short UserSign { get; set; }
        public string ExtDisable { get; set; }
        public string ExtInvsbl { get; set; }
        public short TPLId { get; set; }
        public string TableName { get; set; }
    }
}
