//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRD2
    {
        public string CardCode { get; set; }
        public int LineNum { get; set; }
        public string PymCode { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> ObjType { get; set; }
    }
}
