//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSH
    {
        public string FormID { get; set; }
        public string ItemID { get; set; }
        public string ColID { get; set; }
        public Nullable<short> ActionT { get; set; }
        public Nullable<int> QueryId { get; set; }
        public int IndexID { get; set; }
        public string Refresh { get; set; }
        public string FieldID { get; set; }
        public string FrceRfrsh { get; set; }
        public string ByField { get; set; }
    }
}
