//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBR
    {
        public short UserSign { get; set; }
        public int ToolbarId { get; set; }
        public Nullable<short> Docking { get; set; }
        public Nullable<short> LeftID { get; set; }
        public Nullable<short> TopID { get; set; }
        public Nullable<short> RightID { get; set; }
        public Nullable<short> BottomID { get; set; }
        public string VisibleID { get; set; }
    }
}
