//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CULG
    {
        public int LogId { get; set; }
        public Nullable<int> VersFrom { get; set; }
        public Nullable<int> VersTo { get; set; }
        public string TableId { get; set; }
        public string OnCreate { get; set; }
        public string ErrLevel { get; set; }
        public string InQuery { get; set; }
        public string ErrMessage { get; set; }
        public string UpgStart { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
