//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPC
    {
        public string ObjectId { get; set; }
        public Nullable<int> CntBefore { get; set; }
        public Nullable<int> CntAfter { get; set; }
        public string Reported { get; set; }
    }
}
