//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAL1
    {
        public int AbsEntry { get; set; }
        public Nullable<int> LinkEntry { get; set; }
        public string ItemID { get; set; }
        public string ObjName { get; set; }
        public string PropName { get; set; }
        public string QueryCol { get; set; }
        public string MobDesc { get; set; }
        public string IsUDF { get; set; }
    }
}
