//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLN21
    {
        public int DocEntry { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string RefType { get; set; }
        public int LineNum { get; set; }
        public Nullable<int> RefDocEntr { get; set; }
        public Nullable<int> RefDocNum { get; set; }
        public string ExtDocNum { get; set; }
        public string RefObjType { get; set; }
        public string AccessKey { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuerCNPJ { get; set; }
        public string IssuerCode { get; set; }
        public string Model { get; set; }
        public string Series { get; set; }
        public Nullable<int> Number { get; set; }
        public string RefAccKey { get; set; }
        public Nullable<decimal> RefAmount { get; set; }
        public string SubSeries { get; set; }
        public string Remark { get; set; }
        public string LinkRefTyp { get; set; }
    }
}
