//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPI9
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public Nullable<int> BaseAbs { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public string TargetBase { get; set; }
        public string ObjType { get; set; }
        public Nullable<decimal> DrawnSum { get; set; }
        public Nullable<decimal> DrawnSumFc { get; set; }
        public Nullable<decimal> DrawnSumSc { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjCode { get; set; }
        public Nullable<decimal> ApplDrawn { get; set; }
        public Nullable<decimal> ApplDrawnF { get; set; }
        public Nullable<decimal> ApplDrawnS { get; set; }
        public Nullable<int> BaseDocNum { get; set; }
        public Nullable<System.DateTime> BsDocDate { get; set; }
        public Nullable<System.DateTime> BsDueDate { get; set; }
        public string BsCardName { get; set; }
        public string BsComments { get; set; }
        public string Posted { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> VatFc { get; set; }
        public Nullable<decimal> VatSc { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> GrossFc { get; set; }
        public Nullable<decimal> GrossSc { get; set; }
        public string IsGross { get; set; }
    }
}
