//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPO25
    {
        public int DocEntry { get; set; }
        public string VatGroup { get; set; }
        public Nullable<decimal> VatPrcnt { get; set; }
        public Nullable<decimal> BaseAmnt { get; set; }
        public Nullable<decimal> BaseAmntFC { get; set; }
        public Nullable<decimal> BaseAmntSC { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> VatSumFrgn { get; set; }
        public Nullable<decimal> VatSumSy { get; set; }
        public int Type { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
    }
}
