//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTP1
    {
        public string Code { get; set; }
        public int Level { get; set; }
        public string Base { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> SnapshotId { get; set; }
    }
}
