//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWZ1
    {
        public int WizardId { get; set; }
        public string CardCode { get; set; }
        public string DunAddr { get; set; }
        public string CheckedBP { get; set; }
        public string FaxNum { get; set; }
        public string Email { get; set; }
        public string DPPStatus { get; set; }
    }
}
