//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWZ2
    {
        public int WizardId { get; set; }
        public string CardCode { get; set; }
        public int LetterNum { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public string FeeCurr { get; set; }
        public Nullable<decimal> TtlopnIntr { get; set; }
        public string EDunLevel { get; set; }
        public string OpnIntrCrr { get; set; }
        public int DocAbs { get; set; }
        public Nullable<int> DocNum { get; set; }
        public short InstlmntID { get; set; }
        public Nullable<decimal> IntrstPC { get; set; }
        public Nullable<decimal> IntrstAmnt { get; set; }
        public string IntrstCurr { get; set; }
        public string ChckLine { get; set; }
        public Nullable<int> IntrstDays { get; set; }
        public int DocType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string LetterLvl { get; set; }
        public Nullable<decimal> OpenSum { get; set; }
        public string OpenCurr { get; set; }
        public Nullable<decimal> sumIntrClc { get; set; }
        public string folioNum { get; set; }
        public string LvlUpdated { get; set; }
        public Nullable<decimal> TotalFeeFC { get; set; }
        public Nullable<decimal> TotalFeeLC { get; set; }
        public Nullable<decimal> TotalFeeSC { get; set; }
        public Nullable<decimal> TtlopnInFC { get; set; }
        public Nullable<decimal> TtlopnInSC { get; set; }
        public Nullable<decimal> IntrAmtFC { get; set; }
        public Nullable<decimal> IntrAmtSC { get; set; }
        public Nullable<decimal> OpenSumFC { get; set; }
        public Nullable<decimal> OpenSumSC { get; set; }
        public string ExeChkLine { get; set; }
        public string AutoPost { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<decimal> UnpaidBoEV { get; set; }
        public Nullable<int> BoENumber { get; set; }
        public string BoEStatus { get; set; }
        public Nullable<System.DateTime> BoEDate { get; set; }
        public Nullable<int> BoEKey { get; set; }
        public string BPType { get; set; }
        public Nullable<int> BPLId { get; set; }
    }
}
