//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWZ3
    {
        public int WizardId { get; set; }
        public string CardCode { get; set; }
        public int LetterNum { get; set; }
        public string AddChecked { get; set; }
        public Nullable<int> DocAbs { get; set; }
        public Nullable<decimal> IntrAmt { get; set; }
        public Nullable<decimal> IntrAmtFC { get; set; }
        public Nullable<decimal> IntrAmtSC { get; set; }
        public Nullable<decimal> FeeAmt { get; set; }
        public Nullable<decimal> FeeAmtFC { get; set; }
        public Nullable<decimal> FeeAmtSC { get; set; }
        public string InVatGroup { get; set; }
        public string InTaxCode { get; set; }
        public string FeVatGroup { get; set; }
        public string FeTaxCode { get; set; }
        public Nullable<decimal> VatPrcnt { get; set; }
        public string Executed { get; set; }
        public string Message { get; set; }
        public string DocCur { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> BPLId { get; set; }
        public Nullable<int> LocCode { get; set; }
    }
}
