//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECM4
    {
        public int AbsEntry { get; set; }
        public string Code { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string ObjType { get; set; }
        public string ObjXPath { get; set; }
        public string FieldType { get; set; }
        public string FieldXPath { get; set; }
        public Nullable<int> ImportFmt { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> LogInstanc { get; set; }
    }
}
