//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EML1
    {
        public int AbsEntry { get; set; }
        public int Line { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> DocEntry { get; set; }
    }
}
