//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLT1
    {
        public string FormNo { get; set; }
        public string Code { get; set; }
        public short UserSign { get; set; }
        public Nullable<int> ExNumData1 { get; set; }
        public Nullable<int> ExNumData2 { get; set; }
        public Nullable<int> ExNumData3 { get; set; }
        public string ExStrData1 { get; set; }
        public string ExStrData2 { get; set; }
        public string ExStrData3 { get; set; }
        public string FilterName { get; set; }
    }
}
