//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FNS1
    {
        public int Series { get; set; }
        public int FolNumFrom { get; set; }
        public int FolNumTo { get; set; }
        public string Reason { get; set; }
    }
}
