//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRC1
    {
        public short CatId { get; set; }
        public int TemplateId { get; set; }
        public string AcctCode { get; set; }
        public short VisOrder { get; set; }
        public Nullable<int> CFWId { get; set; }
        public string CalcMethod { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string PrcCode { get; set; }
        public string CalMethod2 { get; set; }
        public string CalMethod3 { get; set; }
        public string Linked { get; set; }
        public string Sign { get; set; }
    }
}
