//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTR3
    {
        public int DocEntry { get; set; }
        public int ItemLine { get; set; }
        public string ItemCode { get; set; }
        public string DprArea { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalFrgn { get; set; }
        public Nullable<decimal> TotalSys { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> LogInstanc { get; set; }
    }
}
