//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBI8
    {
        public int HistoryId { get; set; }
        public int RowId { get; set; }
        public string AcctName { get; set; }
        public string LineNum { get; set; }
        public Nullable<decimal> YearBAmt { get; set; }
        public Nullable<decimal> PerEAmt { get; set; }
        public string RepDate { get; set; }
    }
}
