//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBI9
    {
        public int HistoryId { get; set; }
        public int RowId { get; set; }
        public string RepItm { get; set; }
        public string RepItmNo { get; set; }
        public Nullable<decimal> PeriodAmt { get; set; }
        public Nullable<decimal> YearAmt { get; set; }
    }
}
