//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDP2
    {
        public int AbsEntry { get; set; }
        public short LineNum { get; set; }
        public string NatObjType { get; set; }
        public int NatObjArr { get; set; }
        public string NatObjKey1 { get; set; }
        public string NatObjKey2 { get; set; }
        public Nullable<int> Result { get; set; }
        public string ErrorStr { get; set; }
    }
}
