//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDP3
    {
        public int AbsEntry { get; set; }
        public short LineNum { get; set; }
        public string RefObjType { get; set; }
        public string RefObjKey1 { get; set; }
        public string RefObjKey2 { get; set; }
    }
}
