//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFL1
    {
        public string FormID { get; set; }
        public string GridID { get; set; }
        public short UserCode { get; set; }
        public int FilterID { get; set; }
        public short GridColumn { get; set; }
        public Nullable<short> FilterRule { get; set; }
        public string Value { get; set; }
        public string ValueTo { get; set; }
    }
}
