//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA4
    {
        public int AbsEntry { get; set; }
        public int LineId { get; set; }
        public string LineType { get; set; }
        public Nullable<decimal> CurrCogs { get; set; }
        public Nullable<decimal> CalcCogs { get; set; }
        public Nullable<decimal> CogsDebit { get; set; }
        public Nullable<decimal> CogsCredit { get; set; }
        public string CogsAcct { get; set; }
        public string PrDiffAcct { get; set; }
        public string AutoPost { get; set; }
    }
}
