//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA5
    {
        public int AbsEntry { get; set; }
        public int LineId { get; set; }
        public string Selected { get; set; }
        public string LnType { get; set; }
        public string ProdCode { get; set; }
        public string ProdDescr { get; set; }
        public Nullable<int> PODocAbs { get; set; }
        public Nullable<int> PODocNum { get; set; }
        public string DocType { get; set; }
        public Nullable<int> DocAbs { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> DocLineNum { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescr { get; set; }
        public string DistNumber { get; set; }
        public Nullable<int> SnBAbs { get; set; }
        public Nullable<int> ManagedBy { get; set; }
        public Nullable<decimal> LnQty { get; set; }
        public Nullable<decimal> SnBQty { get; set; }
        public Nullable<decimal> LnCost { get; set; }
        public string DebCred { get; set; }
        public Nullable<decimal> LnTotal { get; set; }
        public Nullable<decimal> SnBTotal { get; set; }
        public Nullable<decimal> SBAccTotal { get; set; }
        public Nullable<decimal> SBAccQty { get; set; }
        public Nullable<decimal> ACAccTotal { get; set; }
        public Nullable<decimal> ACAccQty { get; set; }
        public Nullable<decimal> Applied { get; set; }
        public Nullable<decimal> Variance { get; set; }
        public Nullable<decimal> MRVAdjust { get; set; }
    }
}
