//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTI1
    {
        public int AbsEntry { get; set; }
        public int LineNum { get; set; }
        public string DisctLine { get; set; }
        public string ItemName { get; set; }
        public string ItemSpec { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitPricTp { get; set; }
        public string ItemTaxCat { get; set; }
    }
}
