//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEM3
    {
        public int empID { get; set; }
        public short line { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string reviewDesc { get; set; }
        public Nullable<int> manager { get; set; }
        public string grade { get; set; }
        public string remarks { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string EncryptIV { get; set; }
    }
}
