//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEM5
    {
        public int empID { get; set; }
        public string Object { get; set; }
        public string Peer { get; set; }
        public string Manager { get; set; }
        public string Subord { get; set; }
        public string Dept { get; set; }
        public string Branch { get; set; }
        public string Team { get; set; }
        public Nullable<int> AC { get; set; }
        public string Cmpny { get; set; }
        public string EncryptIV { get; set; }
    }
}
