//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HET1
    {
        public int TransferID { get; set; }
        public int empID { get; set; }
        public Nullable<System.DateTime> Transfered { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public Nullable<short> TransTime { get; set; }
    }
}
