//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HFC2
    {
        public int AbsEntry { get; set; }
        public Nullable<int> FuncID { get; set; }
        public Nullable<int> MainMenu { get; set; }
        public Nullable<int> MovMenuTo { get; set; }
        public Nullable<short> ActionType { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string DataSource { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
