//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HLD1
    {
        public string HldCode { get; set; }
        public System.DateTime StrDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Rmrks { get; set; }
    }
}
