//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMM1
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ViewType { get; set; }
        public string ViewName { get; set; }
        public string MenuDesc { get; set; }
        public string MenuEnable { get; set; }
        public string IAEnable { get; set; }
        public string SLEnable { get; set; }
        public string SLExpose { get; set; }
    }
}
