//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGE23
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string AssetCode { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountSC { get; set; }
        public string SerialNo { get; set; }
        public int VisOrder { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjectType { get; set; }
    }
}
