//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV24
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public int ChildNum { get; set; }
        public Nullable<int> TrackingNt { get; set; }
        public Nullable<int> TrackiNtLn { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string ItemCCDNum { get; set; }
        public string CntrOrigin { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> SubLineNum { get; set; }
    }
}
