//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPF1
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> PriceFOB { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Custom { get; set; }
        public Nullable<decimal> CustomFC { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CostFC { get; set; }
        public Nullable<decimal> PriceAtWH { get; set; }
        public Nullable<decimal> PricAtWHFC { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<decimal> TotalFrgn { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<short> UnitCode { get; set; }
        public Nullable<decimal> Weight1 { get; set; }
        public Nullable<short> UnitCode1 { get; set; }
        public Nullable<decimal> Weight2 { get; set; }
        public Nullable<short> UnitCode2 { get; set; }
        public string CardCode { get; set; }
        public string Reference { get; set; }
        public Nullable<int> OrigLine { get; set; }
        public Nullable<decimal> FactNoCust { get; set; }
        public Nullable<decimal> FacWthCust { get; set; }
        public Nullable<short> PriceList { get; set; }
        public string CostOH { get; set; }
        public string StockEval { get; set; }
        public string UseBaseUn { get; set; }
        public string BlockNum { get; set; }
        public string ImportLog { get; set; }
        public string WhsCode { get; set; }
        public Nullable<int> OrigRow { get; set; }
        public string Locked { get; set; }
        public string OrigWhs { get; set; }
        public Nullable<int> ReleaseNum { get; set; }
        public Nullable<decimal> VarCosts { get; set; }
        public Nullable<decimal> ConstCosts { get; set; }
        public Nullable<decimal> VarCostsFR { get; set; }
        public Nullable<decimal> CnstCostFR { get; set; }
        public Nullable<decimal> UserCustom { get; set; }
        public Nullable<decimal> UsrCusomFC { get; set; }
        public Nullable<decimal> FobValue { get; set; }
        public Nullable<decimal> FobValueFC { get; set; }
        public Nullable<decimal> TtlExpndLC { get; set; }
        public Nullable<decimal> TtlExpndFC { get; set; }
        public Nullable<decimal> TtlCustLC { get; set; }
        public Nullable<decimal> TtlCustFC { get; set; }
        public Nullable<decimal> TtlCostLC { get; set; }
        public Nullable<decimal> TtlCostFC { get; set; }
        public Nullable<decimal> TtlVolume { get; set; }
        public Nullable<decimal> TtlWeight { get; set; }
        public Nullable<int> BaseRowNum { get; set; }
        public Nullable<decimal> TtlCustSC { get; set; }
        public Nullable<decimal> TtlExpndSC { get; set; }
        public Nullable<int> OriBAbsEnt { get; set; }
        public Nullable<int> OriBLinNum { get; set; }
        public Nullable<int> TargetDoc { get; set; }
        public string FobValCurr { get; set; }
        public Nullable<decimal> FobnLaC { get; set; }
        public Nullable<decimal> FobnLaCFC { get; set; }
        public Nullable<decimal> NumPerMsr { get; set; }
        public string Project { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string OriBDocTyp { get; set; }
        public Nullable<decimal> CustRate { get; set; }
        public Nullable<decimal> LFixCost { get; set; }
        public Nullable<decimal> LFixCostFC { get; set; }
        public Nullable<decimal> LVarCost { get; set; }
        public Nullable<decimal> LVarCostFC { get; set; }
        public Nullable<decimal> CstmsRate { get; set; }
        public string VatGroup { get; set; }
        public Nullable<decimal> VatPrcnt { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public string SnbType { get; set; }
        public Nullable<int> SnbAbsEnt { get; set; }
        public Nullable<int> SysNumber { get; set; }
        public string DistNumber { get; set; }
        public Nullable<decimal> ExciseSum { get; set; }
        public Nullable<decimal> ExcisSumFC { get; set; }
        public string ExcInStk { get; set; }
        public Nullable<decimal> CustomSum { get; set; }
        public Nullable<decimal> CustSumFC { get; set; }
        public string CstmInStk { get; set; }
        public Nullable<decimal> CstmVatSum { get; set; }
        public Nullable<decimal> CstmVatFC { get; set; }
        public string CstmVatStk { get; set; }
        public Nullable<int> CCDEntry { get; set; }
        public string CCDNumber { get; set; }
        public Nullable<decimal> ExcisSumSC { get; set; }
        public Nullable<decimal> CustSumSC { get; set; }
        public Nullable<decimal> CstmVatSC { get; set; }
        public Nullable<decimal> InvQty { get; set; }
        public Nullable<int> CCDLineNum { get; set; }
        public Nullable<decimal> TtlVolCCM { get; set; }
        public Nullable<decimal> ExcImpQty { get; set; }
        public Nullable<decimal> ExcFixAmnt { get; set; }
        public Nullable<decimal> ExcRate { get; set; }
        public Nullable<decimal> ExcAmntUoM { get; set; }
        public Nullable<decimal> ExcAmntAdV { get; set; }
        public Nullable<int> ExcImpQUoM { get; set; }
        public Nullable<decimal> ExcBasAmnt { get; set; }
        public Nullable<int> LineNumV3 { get; set; }
        public Nullable<decimal> FobVal2 { get; set; }
        public Nullable<decimal> FobVal2FC { get; set; }
        public string EncryptIV { get; set; }
    }
}
