//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPF2
    {
        public int DocEntry { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string AlcCode { get; set; }
        public string OhType { get; set; }
        public Nullable<decimal> CostSum { get; set; }
        public Nullable<decimal> CostSumFC { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public string CostType { get; set; }
        public string Locked { get; set; }
        public string LaCAllcAcc { get; set; }
        public Nullable<decimal> CostSumSC { get; set; }
        public string InCustCalc { get; set; }
        public Nullable<decimal> OpenCost { get; set; }
        public Nullable<decimal> OpenCostFC { get; set; }
        public Nullable<decimal> OpenCostSC { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string CostCateg { get; set; }
        public string EncryptIV { get; set; }
    }
}
