//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPF3
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string Dscription { get; set; }
        public string LaCAllcAcc { get; set; }
        public Nullable<decimal> CustSum { get; set; }
        public Nullable<decimal> CustSumFC { get; set; }
        public Nullable<decimal> CustSumSC { get; set; }
        public Nullable<decimal> OpenSum { get; set; }
        public Nullable<decimal> OpenSumFC { get; set; }
        public Nullable<decimal> OpenSumSC { get; set; }
        public Nullable<int> AccType { get; set; }
        public string VatGroup { get; set; }
        public string CstmVatStk { get; set; }
        public Nullable<int> CCDEntry { get; set; }
        public Nullable<int> LineNum2 { get; set; }
    }
}
