//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISW1
    {
        public int WizAbsEnt { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public string NatOfTrans { get; set; }
        public string StatProc { get; set; }
        public string CustProc { get; set; }
        public string TransMode { get; set; }
        public string Incoterms { get; set; }
        public string PortEnEx { get; set; }
        public string BPVATRegNo { get; set; }
        public string DomFrgID { get; set; }
        public string CtryOrig { get; set; }
        public string BPCountry { get; set; }
    }
}
