//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITM7
    {
        public string ItemCode { get; set; }
        public string PeriodCat { get; set; }
        public string DprArea { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public Nullable<System.DateTime> DprStart { get; set; }
        public Nullable<System.DateTime> DprEnd { get; set; }
        public Nullable<int> UsefulLife { get; set; }
        public Nullable<decimal> RemainLife { get; set; }
        public string DprType { get; set; }
        public string DprTypeC { get; set; }
        public Nullable<int> UsefulLfeC { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public Nullable<decimal> RemainDays { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<int> RemainUnit { get; set; }
        public Nullable<int> StanUnit { get; set; }
    }
}
