//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT2
    {
        public string Father { get; set; }
        public int StageId { get; set; }
        public int SeqNum { get; set; }
        public Nullable<int> StgEntry { get; set; }
        public string Name { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<decimal> WaitDays { get; set; }
    }
}
