//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVRU
    {
        public int AbsEntry { get; set; }
        public string SourceDB { get; set; }
        public string UtilityDB { get; set; }
        public Nullable<int> IVLGEntry { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string TblHINM { get; set; }
        public string TblHITM { get; set; }
        public string TblHITW { get; set; }
        public string TblFINM { get; set; }
        public string TblFITM { get; set; }
        public string TblFITW { get; set; }
        public Nullable<int> TrSeqHINM { get; set; }
        public Nullable<int> TrSeqOINM { get; set; }
        public Nullable<int> TrIdUtil { get; set; }
        public Nullable<int> TrIdProd { get; set; }
        public string Comment { get; set; }
        public string StrFld { get; set; }
        public Nullable<int> NumFld { get; set; }
    }
}
