//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class JST1
    {
        public int AbsId { get; set; }
        public int LineNum { get; set; }
        public string WTCode { get; set; }
        public Nullable<int> BaseNum { get; set; }
        public Nullable<int> BaseAbsId { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TdsRate { get; set; }
        public Nullable<decimal> SurRate { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public Nullable<decimal> HscRate { get; set; }
        public Nullable<decimal> TaxbleAmnt { get; set; }
        public Nullable<decimal> TxblAmntSC { get; set; }
        public Nullable<decimal> TxblAmntFC { get; set; }
        public string Category { get; set; }
        public string Criteria { get; set; }
        public string Type { get; set; }
        public string RoundType { get; set; }
        public string BaseType { get; set; }
        public string Account { get; set; }
        public string TdsAcc { get; set; }
        public string SurAcc { get; set; }
        public string CessAcc { get; set; }
        public string HscAcc { get; set; }
        public Nullable<decimal> WTAmnt { get; set; }
        public Nullable<decimal> WTAmntSC { get; set; }
        public Nullable<decimal> WTAmntFC { get; set; }
        public Nullable<decimal> TdsBAmt { get; set; }
        public Nullable<decimal> TdsBAmtSC { get; set; }
        public Nullable<decimal> TdsBAmtFC { get; set; }
        public Nullable<decimal> SurBAmt { get; set; }
        public Nullable<decimal> SurBAmtSC { get; set; }
        public Nullable<decimal> SurBAmtFC { get; set; }
        public Nullable<decimal> CessBAmt { get; set; }
        public Nullable<decimal> CessBAmtSC { get; set; }
        public Nullable<decimal> CessBAmtFC { get; set; }
        public Nullable<decimal> HscBAmt { get; set; }
        public Nullable<decimal> HscBAmtSC { get; set; }
        public Nullable<decimal> HscBAmtFC { get; set; }
        public Nullable<decimal> TdsAmnt { get; set; }
        public Nullable<decimal> TdsAmntSC { get; set; }
        public Nullable<decimal> TdsAmntFC { get; set; }
        public Nullable<decimal> SurAmnt { get; set; }
        public Nullable<decimal> SurAmntSC { get; set; }
        public Nullable<decimal> SurAmntFC { get; set; }
        public Nullable<decimal> CessAmnt { get; set; }
        public Nullable<decimal> CessAmntSC { get; set; }
        public Nullable<decimal> CessAmntFC { get; set; }
        public Nullable<decimal> HscAmnt { get; set; }
        public Nullable<decimal> HscAmntSC { get; set; }
        public Nullable<decimal> HscAmntFC { get; set; }
    }
}
