//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPS1
    {
        public string KpsCode { get; set; }
        public int LineNum { get; set; }
        public string KpiName { get; set; }
        public Nullable<decimal> KpiValue1 { get; set; }
        public Nullable<decimal> KpiValue2 { get; set; }
        public Nullable<decimal> KpiValue3 { get; set; }
        public Nullable<decimal> KpiValue4 { get; set; }
        public Nullable<decimal> KpiValue5 { get; set; }
        public Nullable<decimal> KpiValue6 { get; set; }
        public Nullable<decimal> KpiValue7 { get; set; }
        public Nullable<decimal> KpiValue8 { get; set; }
        public Nullable<decimal> KpiValue9 { get; set; }
        public Nullable<decimal> KpiValue10 { get; set; }
        public Nullable<decimal> KpiValue11 { get; set; }
        public Nullable<decimal> KpiValue12 { get; set; }
        public Nullable<decimal> KpiValue13 { get; set; }
        public Nullable<decimal> KpiValue14 { get; set; }
        public Nullable<decimal> KpiValue15 { get; set; }
        public Nullable<decimal> KpiValue16 { get; set; }
        public Nullable<decimal> KpiValue17 { get; set; }
        public Nullable<decimal> KpiValue18 { get; set; }
        public Nullable<decimal> KpiValue19 { get; set; }
        public Nullable<decimal> KpiValue20 { get; set; }
        public Nullable<decimal> KpiValue21 { get; set; }
        public Nullable<decimal> KpiValue22 { get; set; }
        public Nullable<decimal> KpiValue23 { get; set; }
        public Nullable<decimal> KpiValue24 { get; set; }
        public Nullable<decimal> KpiValue25 { get; set; }
        public Nullable<decimal> KpiValue26 { get; set; }
        public Nullable<decimal> KpiValue27 { get; set; }
        public Nullable<decimal> KpiValue28 { get; set; }
        public Nullable<decimal> KpiValue29 { get; set; }
        public Nullable<decimal> KpiValue30 { get; set; }
    }
}
