//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGL1
    {
        public int AbsEntry { get; set; }
        public int LineSeq { get; set; }
        public string LineType { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
