//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDC1
    {
        public int AbsEntry { get; set; }
        public int LineID { get; set; }
        public string ObjectType { get; set; }
        public string ObjectKey { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string Action { get; set; }
        public string ObjectCode { get; set; }
        public string ActFailed { get; set; }
        public string OrigAction { get; set; }
        public string SubObjType { get; set; }
        public string SubObjKey { get; set; }
        public string SubObjNam1 { get; set; }
        public string SubObjNam2 { get; set; }
        public string SubObjNam3 { get; set; }
    }
}
