//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRV2
    {
        public int DocEntry { get; set; }
        public int BaseLine { get; set; }
        public int LineNum { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<decimal> RToStock { get; set; }
        public Nullable<decimal> RActPrice { get; set; }
        public Nullable<int> INMTransNm { get; set; }
        public Nullable<int> INMInst { get; set; }
        public Nullable<int> INMTransTy { get; set; }
        public Nullable<int> INMCreatBy { get; set; }
        public string INMBaseRef { get; set; }
        public Nullable<System.DateTime> INMDocDate { get; set; }
        public Nullable<decimal> INMOpenQty { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<int> IVLTransSe { get; set; }
        public Nullable<int> IVLLayerID { get; set; }
        public Nullable<int> INMLineNum { get; set; }
        public Nullable<int> INMSubLine { get; set; }
    }
}
