//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSN2
    {
        public int AbsEntry { get; set; }
        public string ItemCode { get; set; }
        public int PeriodID { get; set; }
        public Nullable<decimal> Initial { get; set; }
        public Nullable<decimal> InitialOrg { get; set; }
        public Nullable<decimal> InStock { get; set; }
        public Nullable<decimal> OutStock { get; set; }
        public Nullable<decimal> Final { get; set; }
        public Nullable<decimal> FinalOrg { get; set; }
        public Nullable<decimal> Requests { get; set; }
    }
}
