//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class NNM4
    {
        public short ESeries { get; set; }
        public Nullable<int> Series { get; set; }
        public string SeriesName { get; set; }
        public string InitialNum { get; set; }
        public string NextNumber { get; set; }
        public string LastNum { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> ApprovYear { get; set; }
        public Nullable<int> ApprovNum { get; set; }
        public string Remark { get; set; }
    }
}
