//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OADF
    {
        public short Code { get; set; }
        public string Name { get; set; }
        public string Format { get; set; }
        public Nullable<short> UserSign { get; set; }
    }
}
