//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAIB
    {
        public int AlertCode { get; set; }
        public short UserSign { get; set; }
        public string Opened { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<short> RecTime { get; set; }
        public string WasRead { get; set; }
        public string Deleted { get; set; }
        public string Failed { get; set; }
    }
}
