//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALC
    {
        public string AlcCode { get; set; }
        public string AlcName { get; set; }
        public string OhType { get; set; }
        public string AcctCode { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string LaCAllcAcc { get; set; }
        public string CostCateg { get; set; }
    }
}
