//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAMD
    {
        public int LineNum { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string CardCode { get; set; }
        public string Approved { get; set; }
        public Nullable<decimal> AmountDiff { get; set; }
        public Nullable<decimal> TaxAmtDiff { get; set; }
        public string RpCurrency { get; set; }
        public string VendOffAct { get; set; }
    }
}
