//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAOB
    {
        public int AlertCode { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<short> SendTime { get; set; }
        public string WasSent { get; set; }
        public short UserSign { get; set; }
    }
}
