//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OARI
    {
        public int AddOnID { get; set; }
        public string EGroup { get; set; }
        public string AStatus { get; set; }
        public Nullable<int> EventOrder { get; set; }
        public string IsAdd64 { get; set; }
        public string AddPlat { get; set; }
    }
}
