//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDC
    {
        public int Code { get; set; }
        public string Server { get; set; }
        public string License { get; set; }
        public string Company { get; set; }
        public Nullable<int> DBType { get; set; }
        public string DBUser { get; set; }
        public string DBPassword { get; set; }
        public string Username { get; set; }
        public string UPassword { get; set; }
        public string DBTrusted { get; set; }
        public string JCOPath { get; set; }
        public Nullable<int> Language { get; set; }
        public string AddOnIF { get; set; }
        public string StateFder { get; set; }
        public string FormatFder { get; set; }
        public string FileFolder { get; set; }
    }
}
