//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBG
    {
        public int AbsId { get; set; }
        public string Name { get; set; }
        public Nullable<int> BaseId { get; set; }
        public Nullable<decimal> InitRate { get; set; }
        public string Locked { get; set; }
        public System.DateTime FinancYear { get; set; }
        public string IsMain { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> RoundSys { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string PrjCode { get; set; }
    }
}
