//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBOT
    {
        public int AbsEntry { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string StatusFrom { get; set; }
        public string StatusTo { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<short> TranTime { get; set; }
        public string Reconciled { get; set; }
        public Nullable<int> TransId { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
    }
}
