//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCFL
    {
        public int Code { get; set; }
        public Nullable<System.DateTime> DateID { get; set; }
        public string Dscription { get; set; }
        public string Project { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string CredCur { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public string DebCur { get; set; }
        public Nullable<short> SecLevel { get; set; }
        public short UserId { get; set; }
        public string Frequency { get; set; }
        public Nullable<short> Remind { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
    }
}
