//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCFT
    {
        public int CFTId { get; set; }
        public Nullable<int> CFWId { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> SysCredit { get; set; }
        public Nullable<decimal> SysDebit { get; set; }
        public Nullable<decimal> FCDebit { get; set; }
        public Nullable<decimal> FCCredit { get; set; }
        public string FCCurrency { get; set; }
        public string Account { get; set; }
        public Nullable<int> BatchNum { get; set; }
        public Nullable<int> JDTId { get; set; }
        public Nullable<int> JDTLineId { get; set; }
        public string TransType { get; set; }
        public string BaseRef { get; set; }
        public string PaymentMen { get; set; }
        public string PaymentRef { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string Status { get; set; }
    }
}
