//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCFW
    {
        public int CFWId { get; set; }
        public string CFWName { get; set; }
        public string LineNum { get; set; }
        public string Postable { get; set; }
        public Nullable<int> FatherNum { get; set; }
        public Nullable<short> Levels { get; set; }
        public Nullable<short> GroupMask { get; set; }
        public Nullable<int> GroupLine { get; set; }
        public Nullable<int> ExtrMatch { get; set; }
        public Nullable<int> IntrMatch { get; set; }
        public Nullable<int> RateDifCFW { get; set; }
        public Nullable<short> DataSource { get; set; }
        public Nullable<short> Attr { get; set; }
        public Nullable<short> Direction { get; set; }
    }
}
