//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCHH
    {
        public int CheckKey { get; set; }
        public Nullable<int> CheckNum { get; set; }
        public string BankCode { get; set; }
        public string Branch { get; set; }
        public string CashCheck { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Details { get; set; }
        public string CardCode { get; set; }
        public Nullable<System.DateTime> RcptDate { get; set; }
        public Nullable<int> RcptNum { get; set; }
        public Nullable<decimal> CheckSum { get; set; }
        public string Trnsfrable { get; set; }
        public string Deposited { get; set; }
        public string Converted { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> TransNum { get; set; }
        public Nullable<int> DepNum2 { get; set; }
        public Nullable<int> DpstAbs { get; set; }
        public string BankAcct { get; set; }
        public string AcctNum { get; set; }
        public string Currency { get; set; }
        public string Canceled { get; set; }
        public Nullable<int> RcptLineId { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<short> UserID { get; set; }
        public string BankCountr { get; set; }
        public string Project { get; set; }
        public Nullable<int> CanceJEAbs { get; set; }
        public Nullable<int> TempJEAbs { get; set; }
        public string CardName { get; set; }
        public string FiscalID { get; set; }
        public string OrigIssdBy { get; set; }
        public string RejeByBank { get; set; }
        public string EnAcctNum { get; set; }
        public string EncryptIV { get; set; }
        public string DPPStatus { get; set; }
    }
}
