//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCIF
    {
        public int AbsEntry { get; set; }
        public string ISTable { get; set; }
        public string ISField { get; set; }
        public string FieldDesc { get; set; }
        public string FlLocation { get; set; }
        public string FldSource { get; set; }
    }
}
