//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCMN
    {
        public string GUID { get; set; }
        public string Name { get; set; }
        public string Father { get; set; }
        public string Type { get; set; }
        public string SubMenu { get; set; }
        public string MenuUID { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public string ObjectKey { get; set; }
        public Nullable<int> PermFolder { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
