//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCPL
    {
        public int AbsEntry { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndTime { get; set; }
        public string CopySource { get; set; }
        public string CopyTarget { get; set; }
        public string UserName { get; set; }
        public Nullable<short> CopyMethod { get; set; }
        public Nullable<short> FailRpn { get; set; }
        public string MissingUDF { get; set; }
        public Nullable<short> CopyType { get; set; }
        public string ErrorNum { get; set; }
        public Nullable<short> NullifyAct { get; set; }
        public Nullable<short> CopyEmtVal { get; set; }
    }
}
