//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCRV
    {
        public int AbsId { get; set; }
        public int PayId { get; set; }
        public Nullable<short> CreditCard { get; set; }
        public string CrdCardNum { get; set; }
        public Nullable<System.DateTime> CardValid { get; set; }
        public string VoucherNum { get; set; }
        public string OwnerIdNum { get; set; }
        public string OwnerPhone { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string CreditCurr { get; set; }
        public Nullable<decimal> CreditRate { get; set; }
        public string Deposited { get; set; }
        public Nullable<int> DepNum2 { get; set; }
        public Nullable<int> DepNum { get; set; }
        public string AcctCode { get; set; }
        public string VouchAcct { get; set; }
        public string CreditAcct { get; set; }
        public string CardCode { get; set; }
        public Nullable<short> CrTypeCode { get; set; }
        public Nullable<short> NumOfPmnts { get; set; }
        public string Canceled { get; set; }
        public string Storno { get; set; }
        public string Transfered { get; set; }
        public short Instance { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string TransRef { get; set; }
        public string CardName { get; set; }
    }
}
