//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCUL
    {
        public int DocEntry { get; set; }
        public Nullable<int> StartRef { get; set; }
        public Nullable<int> EventType { get; set; }
        public string DateTime { get; set; }
    }
}
