//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCYC
    {
        public short Code { get; set; }
        public string Name { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public string Type { get; set; }
        public string SubOption { get; set; }
        public Nullable<int> Interval { get; set; }
        public string EndType { get; set; }
        public Nullable<int> MaxOccur { get; set; }
        public Nullable<System.DateTime> SeEndDat { get; set; }
        public string Sunday { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public Nullable<int> DayInMonth { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<int> Month { get; set; }
    }
}
