//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODCI
    {
        public int AbsEntry { get; set; }
        public string ConfType { get; set; }
        public string Code { get; set; }
        public string Descr { get; set; }
        public Nullable<decimal> PrcstVal { get; set; }
        public Nullable<int> SuppUnit { get; set; }
        public string Export { get; set; }
        public string Import { get; set; }
        public string StatCode { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string TextVal { get; set; }
        public string ConfID { get; set; }
    }
}
