//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODGP
    {
        public int AbsEntry { get; set; }
        public string SetName { get; set; }
        public string SetDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string Target { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<int> Series { get; set; }
        public string Items { get; set; }
        public string ItemSmmry { get; set; }
        public string Service { get; set; }
        public string ServSmmry { get; set; }
        public string ExchgRate { get; set; }
        public string CreatDraft { get; set; }
        public string BaseQUT { get; set; }
        public string BaseRDR { get; set; }
        public string BaseDLN { get; set; }
        public string BaseRDN { get; set; }
        public string BaseResINV { get; set; }
        public string ExpndSel { get; set; }
        public string SortField { get; set; }
        public string Consolidat { get; set; }
        public string ExpandCons { get; set; }
        public string RCNSummary { get; set; }
        public Nullable<int> ChainCode { get; set; }
        public Nullable<int> OredrNum1 { get; set; }
        public Nullable<int> OredrNum2 { get; set; }
        public string Direct { get; set; }
        public string Indirect { get; set; }
        public string DoReport { get; set; }
        public string FileExport { get; set; }
        public string SavePath { get; set; }
        public string DealNum { get; set; }
        public string UseDirect { get; set; }
        public string NoItmCode { get; set; }
        public string OnData { get; set; }
        public string OnLedger { get; set; }
        public string OnInvnt { get; set; }
        public string Summary { get; set; }
        public string AltItmDocs { get; set; }
        public string PartDelivr { get; set; }
        public string ConsiderBP { get; set; }
        public string ConsiderTy { get; set; }
        public string EDocGenTyp { get; set; }
        public Nullable<short> ESeries { get; set; }
        public string EDocNum { get; set; }
        public string ReopOriRdr { get; set; }
        public string ReopManCls { get; set; }
        public Nullable<short> SeqCode { get; set; }
        public string UseBaseSeq { get; set; }
        public string OnSeqCode { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BlckFrOnly { get; set; }
        public string DocSubType { get; set; }
        public string EDocDflt { get; set; }
    }
}
