//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODPT
    {
        public int DeposId { get; set; }
        public string DeposType { get; set; }
        public Nullable<System.DateTime> DeposDate { get; set; }
        public string DeposCurr { get; set; }
        public string BanckAcct { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> LocTotal { get; set; }
        public Nullable<decimal> FcTotal { get; set; }
        public Nullable<decimal> SysTotal { get; set; }
        public Nullable<int> TransAbs { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public string Splited { get; set; }
        public string VatAct { get; set; }
        public string ComissAct { get; set; }
        public Nullable<decimal> VatTotal { get; set; }
        public Nullable<decimal> Comission { get; set; }
        public Nullable<System.DateTime> ComissDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string DataSource { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public Nullable<decimal> VatTotlSys { get; set; }
        public Nullable<decimal> ComissnSys { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string CommisVat { get; set; }
        public string Project { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public Nullable<decimal> ComisFC { get; set; }
        public Nullable<decimal> VatTotlFC { get; set; }
        public string ComisCurr { get; set; }
    }
}
