//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODUN
    {
        public int LineNum { get; set; }
        public string LetrFormat { get; set; }
        public string EffctAftr { get; set; }
        public Nullable<decimal> LetterFee { get; set; }
        public string FeeCurr { get; set; }
        public Nullable<decimal> MinBalance { get; set; }
        public string MinBlnCurr { get; set; }
        public string CalcIntert { get; set; }
    }
}
