//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODUT
    {
        public string TermCode { get; set; }
        public string TermName { get; set; }
        public string GrpMethod { get; set; }
        public Nullable<short> YearDays { get; set; }
        public Nullable<short> MonthDays { get; set; }
        public string RemIntrst { get; set; }
        public string XchgOrig { get; set; }
        public Nullable<decimal> YearlyRate { get; set; }
        public Nullable<short> MaxLevel { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public string FeeCurr { get; set; }
        public Nullable<decimal> MinBalance { get; set; }
        public string BalCurr { get; set; }
        public string CalcIntr { get; set; }
        public string LetterFrmt { get; set; }
        public string HiLtrFrmt { get; set; }
        public string DateCalInt { get; set; }
        public string AutoPost { get; set; }
        public string IntrAcc { get; set; }
        public string FeeAcc { get; set; }
    }
}
