//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODWZ
    {
        public int WizardId { get; set; }
        public string WizardName { get; set; }
        public Nullable<System.DateTime> ToPayDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Status { get; set; }
        public string DunLevel { get; set; }
        public string CreditZero { get; set; }
        public string PayNoBased { get; set; }
        public string CrdtNBased { get; set; }
        public string DunTime { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ManualJEs { get; set; }
        public string DspOpnItms { get; set; }
        public string AllowNegLt { get; set; }
        public string DunTerm { get; set; }
        public Nullable<System.DateTime> FrmDueDate { get; set; }
        public Nullable<System.DateTime> ToDueDate { get; set; }
        public Nullable<System.DateTime> UpToDate { get; set; }
        public Nullable<System.DateTime> InvPostDat { get; set; }
        public Nullable<System.DateTime> InvDueDate { get; set; }
        public Nullable<System.DateTime> InvDocDate { get; set; }
        public string Project { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string InVatGroup { get; set; }
        public string InTaxCode { get; set; }
        public string FeVatGroup { get; set; }
        public string FeTaxCode { get; set; }
        public Nullable<decimal> VatPrcnt { get; set; }
        public string AutoRmk { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> BPLId { get; set; }
        public Nullable<int> LocCode { get; set; }
        public string VersionNum { get; set; }
        public string OvrDueOnly { get; set; }
        public string QuickDisp { get; set; }
        public string OPNoBased { get; set; }
        public string CnsdVendor { get; set; }
    }
}
