//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OECM
    {
        public string Code { get; set; }
        public string Descr { get; set; }
        public Nullable<short> LogInstanc { get; set; }
        public Nullable<short> UIOrder { get; set; }
        public Nullable<short> StrIndex { get; set; }
        public string IsActive { get; set; }
    }
}
