//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEDG
    {
        public int AbsEntry { get; set; }
        public string Type { get; set; }
        public string ObjType { get; set; }
        public string ObjCode { get; set; }
        public string DiscRel { get; set; }
        public string ValidFor { get; set; }
        public Nullable<System.DateTime> ValidForm { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
