//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEJD
    {
        public int AbsEntry { get; set; }
        public string CRegNum { get; set; }
        public string LFBSheet { get; set; }
        public string LFBSheetPr { get; set; }
        public string RegNum { get; set; }
        public string CmpanyName { get; set; }
    }
}
