//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEML
    {
        public int AbsEntry { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string EMailAddr { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<short> SendTime { get; set; }
        public Nullable<short> USERID { get; set; }
        public string U_NAME { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> AtcEntry { get; set; }
    }
}
