//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEOY
    {
        public string GenrlDefs { get; set; }
        public string ReFiles { get; set; }
        public string ActIndex { get; set; }
        public string ActFromCod { get; set; }
        public string ActToCode { get; set; }
        public string ActGroup { get; set; }
        public string CrdIndex { get; set; }
        public string CrdFromCod { get; set; }
        public string CrdToCode { get; set; }
        public Nullable<short> CrdGrpCust { get; set; }
        public Nullable<short> CrdGrpVndr { get; set; }
        public string CrdToknAnd { get; set; }
        public string CrdUseGrps { get; set; }
        public string CrdClsRang { get; set; }
        public string CrdGrpData { get; set; }
        public string ItmIndex { get; set; }
        public string ItmFromCod { get; set; }
        public string ItmToCode { get; set; }
        public Nullable<short> ItmGroup { get; set; }
        public string ItmToknAnd { get; set; }
        public string ItmUseGrps { get; set; }
        public string ItmClsRang { get; set; }
        public string ItmGrpData { get; set; }
        public string TransfDoc { get; set; }
        public string UnDpsChk { get; set; }
        public string DpsChk { get; set; }
        public string UnDpsVouch { get; set; }
        public string DpsVouch { get; set; }
        public string WorkOrder { get; set; }
        public string RcrTrt { get; set; }
        public string Connection { get; set; }
        public string SpcPrice { get; set; }
        public string Quotations { get; set; }
        public string Orders { get; set; }
        public string DlvrNotes { get; set; }
        public string DlvrInvocs { get; set; }
        public string P_Orders { get; set; }
        public string P_Invoices { get; set; }
        public string ProdTree { get; set; }
        public string Subst { get; set; }
        public string Import { get; set; }
        public string Revert { get; set; }
        public string ActBlnc { get; set; }
        public string ActRef1 { get; set; }
        public string ActRef2 { get; set; }
        public Nullable<System.DateTime> ActRefDate { get; set; }
        public Nullable<System.DateTime> ActDueDate { get; set; }
        public string ActMemo { get; set; }
        public string AOpnBlnAct { get; set; }
        public string AEquetyAct { get; set; }
        public string ActExpLine { get; set; }
        public string ActBlncFrC { get; set; }
        public string ActBlncToC { get; set; }
        public string ActBlncGrp { get; set; }
        public string ActZeroBln { get; set; }
        public string CrdBlnc { get; set; }
        public string CrdRef1 { get; set; }
        public string CrdRef2 { get; set; }
        public Nullable<System.DateTime> CrdRefDate { get; set; }
        public Nullable<System.DateTime> CrdDueDate { get; set; }
        public string CrdMemo { get; set; }
        public string COpnBlnAct { get; set; }
        public string CrdExpLine { get; set; }
        public string CrdBlncFrC { get; set; }
        public string CrdBlncToC { get; set; }
        public Nullable<short> CrdBlncGrC { get; set; }
        public Nullable<short> CrdBlnGrpV { get; set; }
        public string CrdBTknAnd { get; set; }
        public string CrdBUseGrp { get; set; }
        public string CrdBClsRng { get; set; }
        public string CrdBGrpDat { get; set; }
        public string CrdZeroBln { get; set; }
        public string ItmBlnc { get; set; }
        public string ItmRef1 { get; set; }
        public string ItmRef2 { get; set; }
        public Nullable<System.DateTime> ItmRefDate { get; set; }
        public string ItmMemo { get; set; }
        public string ItmBlncFrC { get; set; }
        public string ItmBlncToC { get; set; }
        public Nullable<short> ItmBlncGrp { get; set; }
        public string ItmBTknAnd { get; set; }
        public string ItmBUseGrp { get; set; }
        public string ItmBClsRng { get; set; }
        public string ItmBGrpDat { get; set; }
        public Nullable<short> ItmPlnNum { get; set; }
        public string ItmZeroPr { get; set; }
        public string FileReport { get; set; }
        public string CompName { get; set; }
        public string WasGnrlDef { get; set; }
        public string P_DlvrNots { get; set; }
        public string Spg { get; set; }
        public string Pdn { get; set; }
        public string PdnClosed { get; set; }
        public string Rpd { get; set; }
        public string ReportTemp { get; set; }
        public string Confirmat { get; set; }
        public string DocDraft { get; set; }
        public string ChkOutDrft { get; set; }
        public string OptOpen { get; set; }
        public string OptClosed { get; set; }
        public string SerBtchNum { get; set; }
        public string CorrInvoic { get; set; }
        public Nullable<short> UserGign { get; set; }
        public string PaymDraf { get; set; }
        public string PaymentWiz { get; set; }
        public string AltItems { get; set; }
        public string DPIInvoice { get; set; }
        public string DPIRequest { get; set; }
        public string Ctr { get; set; }
        public string Ins { get; set; }
        public string CorrAPInv { get; set; }
        public string CorrAPRev { get; set; }
        public string CorrARInv { get; set; }
        public string CorrARRev { get; set; }
        public string UserObj { get; set; }
        public string AdWrkOrdr { get; set; }
        public string DPOInvoice { get; set; }
        public string DPORequest { get; set; }
        public string P_Quotatio { get; set; }
        public string WTQ { get; set; }
        public string Oat { get; set; }
        public string CPN { get; set; }
        public string AdvRules { get; set; }
        public string Prq { get; set; }
    }
}
