//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFAR
    {
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> AssetDate { get; set; }
        public string Ref { get; set; }
        public string Comments { get; set; }
        public string JrnlMemo { get; set; }
        public string DprArea { get; set; }
        public Nullable<int> TransId { get; set; }
        public string Handwrtten { get; set; }
        public string PIndicator { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BPLName { get; set; }
        public string VatRegNum { get; set; }
        public Nullable<decimal> RevalPerc { get; set; }
    }
}
