//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFN
    {
        public int Series { get; set; }
        public string Name { get; set; }
        public string PTICode { get; set; }
        public Nullable<int> FirstNum { get; set; }
        public Nullable<int> NextNum { get; set; }
        public Nullable<int> LastNum { get; set; }
        public string Letter { get; set; }
        public string CAI { get; set; }
        public Nullable<System.DateTime> CAIDueDate { get; set; }
        public string Remarks { get; set; }
        public string Locked { get; set; }
    }
}
