//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFRC
    {
        public short CatId { get; set; }
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public string FrgnName { get; set; }
        public Nullable<short> Levels { get; set; }
        public Nullable<short> FatherNum { get; set; }
        public string Active { get; set; }
        public string HasSons { get; set; }
        public Nullable<short> VisOrder { get; set; }
        public string SubSum { get; set; }
        public string SubName { get; set; }
        public string Furmula { get; set; }
        public Nullable<short> Param_1 { get; set; }
        public Nullable<short> Param_2 { get; set; }
        public Nullable<short> Param_3 { get; set; }
        public Nullable<short> Param_4 { get; set; }
        public Nullable<short> Param_5 { get; set; }
        public Nullable<short> Param_6 { get; set; }
        public Nullable<short> Param_7 { get; set; }
        public Nullable<short> Param_8 { get; set; }
        public Nullable<short> Param_9 { get; set; }
        public Nullable<short> Param_10 { get; set; }
        public Nullable<short> Param_11 { get; set; }
        public Nullable<short> Param_12 { get; set; }
        public Nullable<short> Param_13 { get; set; }
        public Nullable<short> Param_14 { get; set; }
        public Nullable<short> Param_15 { get; set; }
        public Nullable<short> Param_16 { get; set; }
        public Nullable<short> Param_17 { get; set; }
        public Nullable<short> Param_18 { get; set; }
        public Nullable<short> Param_19 { get; set; }
        public Nullable<short> Param_20 { get; set; }
        public Nullable<short> Param_21 { get; set; }
        public Nullable<short> Param_22 { get; set; }
        public Nullable<short> Param_23 { get; set; }
        public Nullable<short> Param_24 { get; set; }
        public Nullable<short> Param_25 { get; set; }
        public string OP_1 { get; set; }
        public string OP_2 { get; set; }
        public string OP_3 { get; set; }
        public string OP_4 { get; set; }
        public string OP_5 { get; set; }
        public string OP_6 { get; set; }
        public string OP_7 { get; set; }
        public string OP_8 { get; set; }
        public string OP_9 { get; set; }
        public string OP_10 { get; set; }
        public string OP_11 { get; set; }
        public string OP_12 { get; set; }
        public string OP_13 { get; set; }
        public string OP_14 { get; set; }
        public string OP_15 { get; set; }
        public string OP_16 { get; set; }
        public string OP_17 { get; set; }
        public string OP_18 { get; set; }
        public string OP_19 { get; set; }
        public string OP_20 { get; set; }
        public string OP_21 { get; set; }
        public string OP_22 { get; set; }
        public string OP_23 { get; set; }
        public string OP_24 { get; set; }
        public string ProfitLoss { get; set; }
        public string MoveNeg { get; set; }
        public string Dummy { get; set; }
        public string HideAct { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> ToGroup { get; set; }
        public Nullable<short> ToTitle { get; set; }
        public string LineNum { get; set; }
        public string IndentChar { get; set; }
        public string Reversal { get; set; }
        public string TextTitle { get; set; }
        public string SumType { get; set; }
        public string NetIncome { get; set; }
        public Nullable<int> PLTempId { get; set; }
        public string CustName { get; set; }
        public string ExtFromBS { get; set; }
        public string ExtData { get; set; }
        public string LegalRef { get; set; }
        public Nullable<short> PLCatId { get; set; }
        public string SignAggr { get; set; }
        public string Mandatory { get; set; }
        public string AcctReq { get; set; }
        public string NotPermit { get; set; }
        public string KPIFactor { get; set; }
        public string CatCode { get; set; }
        public string CatClass { get; set; }
    }
}
