//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGFL
    {
        public string FormID { get; set; }
        public string GridID { get; set; }
        public short UserCode { get; set; }
        public Nullable<int> DefFilter { get; set; }
        public Nullable<int> NextFltID { get; set; }
    }
}
