//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGTI
    {
        public int AbsEntry { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string MappingNum { get; set; }
        public string Voiding { get; set; }
        public string ItemList { get; set; }
        public string CategNum { get; set; }
        public string GtsInvNum { get; set; }
        public Nullable<int> ItemRowNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<short> FiscaMonth { get; set; }
        public Nullable<decimal> DocAmount { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public string BpName { get; set; }
        public string BpTaxRgNum { get; set; }
        public string BpAddrTel { get; set; }
        public string BpBankNum { get; set; }
        public string SellerName { get; set; }
        public string SelTaxReg { get; set; }
        public string SelAddTel { get; set; }
        public string SelBankAct { get; set; }
        public string Remarks { get; set; }
        public string Issuer { get; set; }
        public string Checker { get; set; }
        public string Payee { get; set; }
        public string InBndFile { get; set; }
    }
}
