//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OILM
    {
        public int MessageID { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<int> DocLineNum { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> EffectQty { get; set; }
        public Nullable<short> LocType { get; set; }
        public string LocCode { get; set; }
        public Nullable<decimal> TotalLC { get; set; }
        public Nullable<decimal> TotalFC { get; set; }
        public Nullable<decimal> TotalSC { get; set; }
        public Nullable<int> BaseAbsEnt { get; set; }
        public Nullable<int> BaseType { get; set; }
        public string BaseCurr { get; set; }
        public string Currency { get; set; }
        public Nullable<int> AccumType { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<decimal> ExpensesLC { get; set; }
        public Nullable<decimal> ExpensesFC { get; set; }
        public Nullable<decimal> ExpensesSC { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string ItemCode { get; set; }
        public string BPCardCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public string Comment { get; set; }
        public string JrnlMemo { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<int> SnBType { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public string DataSource { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public Nullable<decimal> DocPrice { get; set; }
        public string CardName { get; set; }
        public string Dscription { get; set; }
        public string TreeType { get; set; }
        public Nullable<int> ApplObj { get; set; }
        public Nullable<int> AppObjAbs { get; set; }
        public string AppObjType { get; set; }
        public Nullable<int> AppObjLine { get; set; }
        public string BASE_REF { get; set; }
        public Nullable<int> TransSeqRf { get; set; }
        public Nullable<int> LayerIDRef { get; set; }
        public string VersionNum { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public string PriceCurr { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> CIShbQty { get; set; }
        public Nullable<int> SubLineNum { get; set; }
        public string PrjCode { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string UseDocPric { get; set; }
        public string VendorNum { get; set; }
        public string SerialNum { get; set; }
        public string BlockNum { get; set; }
        public string ImportLog { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<decimal> DocPrcRate { get; set; }
        public string DocPrcCurr { get; set; }
        public string CgsOcrCod { get; set; }
        public string CgsOcrCod2 { get; set; }
        public string CgsOcrCod3 { get; set; }
        public string CgsOcrCod4 { get; set; }
        public string CgsOcrCod5 { get; set; }
        public Nullable<int> BSubLineNo { get; set; }
        public Nullable<int> AppSubLine { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<decimal> SysRate { get; set; }
        public string ExFromRpt { get; set; }
        public string Ref3 { get; set; }
        public string EnSetCost { get; set; }
        public Nullable<decimal> RetCost { get; set; }
        public Nullable<int> DocAction { get; set; }
        public string UseShpdGd { get; set; }
        public Nullable<decimal> AddTotalLC { get; set; }
        public Nullable<decimal> AddExpLC { get; set; }
        public string IsNegLnQty { get; set; }
        public Nullable<int> StgSeqNum { get; set; }
        public Nullable<int> StgEntry { get; set; }
        public string StgDesc { get; set; }
    }
}
