//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIPD
    {
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> DocTime { get; set; }
        public string IOffIncAcc { get; set; }
        public string DOffDecAcc { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Reference { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string VersionNum { get; set; }
        public Nullable<int> JdtNum { get; set; }
        public string Reference2 { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> PriceSrc { get; set; }
        public Nullable<int> PriceList { get; set; }
        public string JrnlMemo { get; set; }
        public string Status { get; set; }
        public Nullable<int> LogIns { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CountDate { get; set; }
        public Nullable<int> CountTime { get; set; }
        public string WddStatus { get; set; }
        public Nullable<int> DraftKey { get; set; }
        public string Printed { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BPLName { get; set; }
        public Nullable<int> UpdateTS { get; set; }
        public string CopyOption { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public string PIndicator { get; set; }
        public Nullable<int> FinncPriod { get; set; }
    }
}
