//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIPF
    {
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string SuppName { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string DocStatus { get; set; }
        public string AgentNum { get; set; }
        public string Descr { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string DocCur { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<decimal> ExpCustom { get; set; }
        public Nullable<decimal> ActCustom { get; set; }
        public Nullable<decimal> Vat1 { get; set; }
        public Nullable<decimal> Vat2 { get; set; }
        public Nullable<decimal> BeforeVat { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<decimal> CostSum { get; set; }
        public Nullable<short> DocTime { get; set; }
        public string Canceled { get; set; }
        public Nullable<decimal> ExCustomFC { get; set; }
        public Nullable<decimal> AcCustomFC { get; set; }
        public Nullable<decimal> Vat1FC { get; set; }
        public Nullable<decimal> Vat2FC { get; set; }
        public Nullable<decimal> BeforVatFC { get; set; }
        public Nullable<decimal> DocTotalFC { get; set; }
        public Nullable<decimal> CostSumFC { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> Cost_Match { get; set; }
        public Nullable<decimal> C_Match_FC { get; set; }
        public string BillOfLad { get; set; }
        public Nullable<short> TrnspCode { get; set; }
        public Nullable<decimal> CostFactor { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Transfered { get; set; }
        public short Instance { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public int Series { get; set; }
        public Nullable<int> JdtNum { get; set; }
        public string JdtMemo { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string ObjType { get; set; }
        public Nullable<decimal> ExCustomSC { get; set; }
        public Nullable<decimal> ActCustSC { get; set; }
        public Nullable<decimal> TtlCostSC { get; set; }
        public string VersionNum { get; set; }
        public string OpenForLaC { get; set; }
        public string incCustom { get; set; }
        public Nullable<short> SeqCode { get; set; }
        public Nullable<int> Serial { get; set; }
        public string SeriesStr { get; set; }
        public string SubStr { get; set; }
        public string BuildDesc { get; set; }
        public string SupplCode { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public Nullable<System.DateTime> CustDate { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string DPPStatus { get; set; }
        public string EncryptIV { get; set; }
    }
}
