//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OISR
    {
        public int RequestNum { get; set; }
        public Nullable<System.DateTime> Open_Date { get; set; }
        public Nullable<int> Open_Time { get; set; }
        public Nullable<int> Task_Id { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public Nullable<short> TaskType { get; set; }
        public string Dscription { get; set; }
        public string Answer { get; set; }
        public string Status { get; set; }
    }
}
