//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OITL
    {
        public int LogEntry { get; set; }
        public Nullable<int> TransId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ManagedBy { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocLine { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> ApplyEntry { get; set; }
        public Nullable<int> ApplyLine { get; set; }
        public Nullable<int> ApplyType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<decimal> DocQty { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> DefinedQty { get; set; }
        public Nullable<int> StockEff { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> LocType { get; set; }
        public string LocCode { get; set; }
        public Nullable<int> AppDocNum { get; set; }
        public string VersionNum { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> SubLineNum { get; set; }
        public Nullable<int> BSubLineNo { get; set; }
        public Nullable<int> AppSubLine { get; set; }
        public Nullable<int> ActBaseTp { get; set; }
        public Nullable<int> ActBaseEnt { get; set; }
        public Nullable<int> ActBaseLn { get; set; }
        public Nullable<int> ActBasSubL { get; set; }
        public Nullable<int> AllocateTp { get; set; }
        public Nullable<int> AllocatEnt { get; set; }
        public Nullable<int> AllocateLn { get; set; }
        public Nullable<short> CreateTime { get; set; }
    }
}
