//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OITR
    {
        public int ReconNum { get; set; }
        public string IsCard { get; set; }
        public string ReconType { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ReconCurr { get; set; }
        public string Canceled { get; set; }
        public Nullable<int> CancelAbs { get; set; }
        public string IsSystem { get; set; }
        public string InitObjTyp { get; set; }
        public Nullable<int> InitObjAbs { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string ReconRule1 { get; set; }
        public string ReconRule2 { get; set; }
        public string ReconRule3 { get; set; }
        public string IsMultiBP { get; set; }
        public string VersionNum { get; set; }
        public Nullable<int> OldMatNum { get; set; }
        public Nullable<int> ReconJEId { get; set; }
        public string BuildDesc { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BPLName { get; set; }
        public string VATRegNum { get; set; }
        public string IsElectr { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public Nullable<int> UpdateTS { get; set; }
        public string ObjType { get; set; }
    }
}
