//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIWZ
    {
        public int AbsEntry { get; set; }
        public string WizName { get; set; }
        public Nullable<System.DateTime> PostDateTo { get; set; }
        public string WizType { get; set; }
        public string IndexCode { get; set; }
        public Nullable<decimal> IndexRate { get; set; }
        public string CashAcct { get; set; }
        public Nullable<decimal> CashFrmBl { get; set; }
        public string CashCancel { get; set; }
        public string FromItem { get; set; }
        public string ToItem { get; set; }
        public Nullable<short> ItemGroup { get; set; }
        public string Properties { get; set; }
        public string RvalMethod { get; set; }
        public Nullable<short> PriceSour { get; set; }
        public Nullable<int> TransAbs { get; set; }
        public string UseDLN { get; set; }
        public string UsePCH { get; set; }
        public string UsePCHNoSt { get; set; }
        public string UseImport { get; set; }
        public Nullable<decimal> CashDifBal { get; set; }
        public string CashExecut { get; set; }
        public string ActType { get; set; }
        public Nullable<decimal> VarRate { get; set; }
        public string FilterExe { get; set; }
        public Nullable<int> CashErrRes { get; set; }
        public string CshRvToAct { get; set; }
        public string MarkVar { get; set; }
        public string ChngPrice { get; set; }
        public string UseSemestr { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> CshLstRvBl { get; set; }
        public Nullable<short> userSign { get; set; }
        public Nullable<short> userSign2 { get; set; }
        public Nullable<System.DateTime> CshCanclD { get; set; }
    }
}
