//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMAO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string Type { get; set; }
        public string Provider { get; set; }
        public string ViewStyle { get; set; }
        public string LogonMethd { get; set; }
        public string LogonPyld { get; set; }
        public string Enable { get; set; }
        public string System { get; set; }
        public string B1MobileAp { get; set; }
        public string B1SalesApp { get; set; }
        public string B1SrvcApp { get; set; }
    }
}
