//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMDP
    {
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public Nullable<int> Series { get; set; }
        public string PeriodCat { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocStatus { get; set; }
        public Nullable<int> TransId { get; set; }
        public string Comments { get; set; }
        public string Reference { get; set; }
        public string ObjType { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<decimal> SysRate { get; set; }
        public string PIndicator { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<decimal> DocTotalFC { get; set; }
        public Nullable<decimal> DocTotalSy { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string TransType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string JrnlMemo { get; set; }
        public Nullable<System.DateTime> AssetDate { get; set; }
        public string CurSource { get; set; }
        public string DocType { get; set; }
        public string PrjSmarz { get; set; }
        public string DstRlSmarz { get; set; }
        public string ManDprType { get; set; }
        public string Handwrtten { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string DprArea { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BaseRef { get; set; }
        public string LVARetire { get; set; }
        public Nullable<short> CancelOpt { get; set; }
        public string BPLName { get; set; }
        public string VatRegNum { get; set; }
        public string GdsMovType { get; set; }
    }
}
