//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMPF
    {
        public int MessageUid { get; set; }
        public int FormUid { get; set; }
        public short UserSign { get; set; }
        public Nullable<int> SelctedBtn { get; set; }
    }
}
