//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMSG
    {
        public short USERID { get; set; }
        public string Signature { get; set; }
        public string UseCompSig { get; set; }
        public string DummySig { get; set; }
    }
}
