//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONFT
    {
        public int AbsId { get; set; }
        public string Code { get; set; }
        public string Locked { get; set; }
        public Nullable<int> GPCId { get; set; }
    }
}
