//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OOAT
    {
        public int AbsID { get; set; }
        public string BpCode { get; set; }
        public string BpName { get; set; }
        public Nullable<int> CntctCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public string Descript { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> Owner { get; set; }
        public string Renewal { get; set; }
        public string UseDiscnt { get; set; }
        public Nullable<short> RemindVal { get; set; }
        public string RemindUnit { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AtchEntry { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdtDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Cancelled { get; set; }
        public string DataSource { get; set; }
        public string Transfered { get; set; }
        public string RemindFlg { get; set; }
        public string Fulfilled { get; set; }
        public string Attachment { get; set; }
        public Nullable<decimal> SettleProb { get; set; }
        public Nullable<int> UpdtTime { get; set; }
        public string Method { get; set; }
        public Nullable<short> GroupNum { get; set; }
        public Nullable<short> ListNum { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<int> AmendedTo { get; set; }
        public Nullable<int> Series { get; set; }
        public int Number { get; set; }
        public string ObjType { get; set; }
        public string Handwrtten { get; set; }
        public string PIndicator { get; set; }
        public string BpType { get; set; }
        public short Instance { get; set; }
        public string PayMethod { get; set; }
        public string NumAtCard { get; set; }
        public string BPCurr { get; set; }
        public Nullable<decimal> FixedRate { get; set; }
        public Nullable<short> TrnspCode { get; set; }
        public string Project { get; set; }
        public string PriceMode { get; set; }
        public string WddStatus { get; set; }
        public string FromStat { get; set; }
        public string DPPStatus { get; set; }
        public string SAPPassprt { get; set; }
        public string EncryptIV { get; set; }
    }
}
