//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OOCR
    {
        public string OcrCode { get; set; }
        public string OcrName { get; set; }
        public Nullable<decimal> OcrTotal { get; set; }
        public string Direct { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> DimCode { get; set; }
        public Nullable<int> AbsEntry { get; set; }
        public string Active { get; set; }
        public Nullable<int> logInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string IsFixedAmt { get; set; }
    }
}
