//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPKG
    {
        public int PkgCode { get; set; }
        public string PkgType { get; set; }
        public Nullable<decimal> Length1 { get; set; }
        public Nullable<short> Len1Unit { get; set; }
        public Nullable<decimal> length2 { get; set; }
        public Nullable<short> Len2Unit { get; set; }
        public Nullable<decimal> Width1 { get; set; }
        public Nullable<short> Wdth1Unit { get; set; }
        public Nullable<decimal> Width2 { get; set; }
        public Nullable<short> Wdth2Unit { get; set; }
        public Nullable<decimal> Height1 { get; set; }
        public Nullable<short> Hght1Unit { get; set; }
        public Nullable<decimal> Height2 { get; set; }
        public Nullable<short> Hght2Unit { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<short> VolUnit { get; set; }
        public Nullable<decimal> Weight1 { get; set; }
        public Nullable<short> WghtUnit { get; set; }
        public Nullable<decimal> Weight2 { get; set; }
        public Nullable<short> Wght2Unit { get; set; }
    }
}
