//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPQW
    {
        public int AbsEntry { get; set; }
        public string SetName { get; set; }
        public string SetDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string CreatDraft { get; set; }
        public string GroupBy { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public Nullable<int> BPLId { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string BaseOn { get; set; }
    }
}
