//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPR1
    {
        public int OpprId { get; set; }
        public short Line { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public Nullable<int> CntctCode { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> Step_Id { get; set; }
        public Nullable<decimal> ClosePrcnt { get; set; }
        public Nullable<decimal> MaxSumLoc { get; set; }
        public Nullable<decimal> MaxSumSys { get; set; }
        public string Memo { get; set; }
        public Nullable<int> DocId { get; set; }
        public string ObjType { get; set; }
        public string Status { get; set; }
        public string Linked { get; set; }
        public Nullable<decimal> WtSumLoc { get; set; }
        public Nullable<decimal> WtSumSys { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string ChnCrdCode { get; set; }
        public string ChnCrdName { get; set; }
        public Nullable<int> ChnCrdCon { get; set; }
        public string DocChkbox { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> DocNumber { get; set; }
        public string EncryptIV { get; set; }
    }
}
