//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPR3
    {
        public int OpportId { get; set; }
        public short Line { get; set; }
        public Nullable<int> CompetId { get; set; }
        public string Memo { get; set; }
        public string Won { get; set; }
        public Nullable<short> ThreatLevl { get; set; }
        public string EncryptIV { get; set; }
    }
}
