//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPRA
    {
        public int AbsEntry { get; set; }
        public string CateType { get; set; }
        public string CateCode { get; set; }
        public string Category { get; set; }
        public string Account { get; set; }
    }
}
