//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORCL
    {
        public int AbsEntry { get; set; }
        public Nullable<int> RcpEntry { get; set; }
        public Nullable<int> Instance { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string Status { get; set; }
        public string DocObjType { get; set; }
        public Nullable<int> DocEntry { get; set; }
    }
}
