//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORCM
    {
        public int DocEntry { get; set; }
        public Nullable<int> ObjAbs { get; set; }
        public Nullable<int> ObjType { get; set; }
        public string ItemCode { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string OrderType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UOM { get; set; }
        public string CardCode { get; set; }
        public string Warehouse { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public string Origin { get; set; }
        public string Status { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<short> DocTime { get; set; }
        public Nullable<int> BPLid { get; set; }
        public Nullable<decimal> PriceBefDi { get; set; }
        public Nullable<decimal> DiscPrcnt { get; set; }
        public Nullable<System.DateTime> ReleasDate { get; set; }
        public Nullable<decimal> PriceAftV { get; set; }
        public string FromWhse { get; set; }
        public Nullable<System.DateTime> FstReqDate { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public Nullable<decimal> NumPerMsr { get; set; }
        public Nullable<int> AgrNo { get; set; }
        public Nullable<int> AgrLnNum { get; set; }
        public string UseDiscnt { get; set; }
        public string PriceMode { get; set; }
        public string RouDatCalc { get; set; }
    }
}
