//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OREQ
    {
        public int AbsEntry { get; set; }
        public Nullable<int> Category { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateTime { get; set; }
        public Nullable<System.DateTime> LstUpdDate { get; set; }
        public Nullable<int> LstUpdTime { get; set; }
        public string UserSign { get; set; }
        public Nullable<int> Port { get; set; }
    }
}
