//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORLD
    {
        public int AbsEntry { get; set; }
        public string ObjectCode { get; set; }
        public string DocSubType { get; set; }
        public string Status { get; set; }
    }
}
