//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORTL
    {
        public int LogEntry { get; set; }
        public string ResCode { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocLine { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<short> LocType { get; set; }
        public string LocCode { get; set; }
        public string VersionNum { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<decimal> DocQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<decimal> OpenQty { get; set; }
        public string DocNum { get; set; }
        public string BaseDocNum { get; set; }
        public Nullable<int> StgSeqNum { get; set; }
        public Nullable<int> StgEntry { get; set; }
        public string StgDesc { get; set; }
    }
}
