//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORTM
    {
        public int LineNum { get; set; }
        public Nullable<System.DateTime> Rtmdate { get; set; }
        public string AcctCode { get; set; }
        public string IsCard { get; set; }
        public string ActCurrncy { get; set; }
        public Nullable<decimal> ActRate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> FrnBlnc { get; set; }
        public Nullable<int> TransNum { get; set; }
        public string Valid { get; set; }
        public Nullable<decimal> Delta { get; set; }
        public string IsSysCurr { get; set; }
        public Nullable<System.DateTime> StornoDate { get; set; }
        public Nullable<decimal> RevalRate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> BPLId { get; set; }
        public Nullable<decimal> CntBlnc { get; set; }
        public Nullable<decimal> TransAmtSC { get; set; }
        public Nullable<decimal> BalDueSC { get; set; }
        public string SCAdjust { get; set; }
    }
}
