//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORTW
    {
        public int AbsEntry { get; set; }
        public Nullable<System.DateTime> WDueDtFrom { get; set; }
        public Nullable<System.DateTime> WDueDtTo { get; set; }
        public string WImpFile { get; set; }
        public Nullable<int> WMatching { get; set; }
        public Nullable<int> WBoletosAu { get; set; }
        public Nullable<int> WBoletosMn { get; set; }
        public Nullable<int> WBoletosNI { get; set; }
        public Nullable<System.DateTime> WRelDate { get; set; }
        public Nullable<int> WCollDisc { get; set; }
        public string WBankAcc1 { get; set; }
        public string WBankAcc2 { get; set; }
        public string WFileForm2 { get; set; }
    }
}
