//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSPG
    {
        public string CardCode { get; set; }
        public string ObjType { get; set; }
        public string ObjKey { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
    }
}
