//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSPP
    {
        public string ItemCode { get; set; }
        public string CardCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<short> ListNum { get; set; }
        public string AutoUpdt { get; set; }
        public string EXPAND { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> SrcPrice { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Valid { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
    }
}
