//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUL
    {
        public int ID { get; set; }
        public string RealName { get; set; }
        public string LogReason { get; set; }
        public string LogDetail { get; set; }
        public string Mac { get; set; }
        public string Machine { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EndTime { get; set; }
        public string ChkHash { get; set; }
    }
}
