//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSWA
    {
        public string PymntRsnCd { get; set; }
        public string CardCode { get; set; }
        public Nullable<decimal> FllTxInAdv { get; set; }
        public Nullable<decimal> AmntsOnhld { get; set; }
        public Nullable<decimal> RTAsWth { get; set; }
        public Nullable<decimal> RTAsAdv { get; set; }
        public Nullable<decimal> SspndRegTx { get; set; }
        public Nullable<decimal> MTAsWth { get; set; }
        public Nullable<decimal> MTAsAdv { get; set; }
        public Nullable<decimal> SspndMTTx { get; set; }
        public Nullable<decimal> TxblPrYr { get; set; }
        public Nullable<decimal> WTHPrYr { get; set; }
        public Nullable<decimal> ScrtyCntrP { get; set; }
        public Nullable<decimal> ScrtyCntrS { get; set; }
        public Nullable<decimal> ExpsRmbrsd { get; set; }
        public Nullable<decimal> WTHRmbrsd { get; set; }
        public string DlvryIdNo { get; set; }
        public string SnglCrtfNo { get; set; }
        public Nullable<short> ErnYr { get; set; }
        public string Advanced { get; set; }
        public string WTHTypCd { get; set; }
        public Nullable<decimal> GrssAmount { get; set; }
        public Nullable<decimal> NtSbjctFrg { get; set; }
        public Nullable<decimal> TxblAmnt { get; set; }
        public Nullable<decimal> WTHAmnt { get; set; }
        public string SSFiscalCd { get; set; }
        public string SSIName { get; set; }
        public string SSICode { get; set; }
        public string CompanyCd { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> EmpeSSCntr { get; set; }
        public Nullable<decimal> EmprSSCntr { get; set; }
        public string OthCntrbts { get; set; }
        public Nullable<decimal> VOthCntrbt { get; set; }
        public Nullable<decimal> OthAmntDue { get; set; }
        public Nullable<decimal> OthAmntPd { get; set; }
        public Nullable<decimal> AmntPdBfBr { get; set; }
        public Nullable<decimal> AmntPdByTr { get; set; }
        public string FiscalCode { get; set; }
        public Nullable<decimal> TxblAmntE { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TxAmntInAd { get; set; }
        public Nullable<decimal> SspndWTHTx { get; set; }
        public Nullable<decimal> AdRgTxIRPH { get; set; }
        public Nullable<decimal> AdRgTxIRPA { get; set; }
        public Nullable<decimal> SspdRgnlTx { get; set; }
        public Nullable<decimal> AdCtTxIRWT { get; set; }
        public Nullable<decimal> AdCtTxIWTA { get; set; }
        public Nullable<decimal> SspndCtTx { get; set; }
        public string FsCdTrdPty { get; set; }
        public string FCdTrdPtyS { get; set; }
        public string FscCdExpr { get; set; }
        public string FsCdMnDbS { get; set; }
        public Nullable<decimal> AmntPdS { get; set; }
        public Nullable<decimal> WHTApdS { get; set; }
        public string WHTNApdS { get; set; }
        public string FsCdMnDbR { get; set; }
        public Nullable<decimal> AmntPdR { get; set; }
        public Nullable<decimal> WHTApdR { get; set; }
        public string WHTNApdR { get; set; }
        public Nullable<decimal> AmntPdA { get; set; }
        public Nullable<decimal> TxAppldA { get; set; }
        public Nullable<decimal> AmntPdB { get; set; }
        public Nullable<decimal> TxAppldB { get; set; }
        public Nullable<decimal> AmntPdC { get; set; }
        public Nullable<decimal> TxAppldC { get; set; }
        public Nullable<decimal> AmntPdD { get; set; }
        public Nullable<decimal> TxAppldD { get; set; }
        public Nullable<decimal> AmtPvdNTxS { get; set; }
        public Nullable<decimal> AmtPvdNTxR { get; set; }
    }
}
