//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTCD
    {
        public int AbsId { get; set; }
        public string TcdType { get; set; }
        public string DftArCode { get; set; }
        public string DftApCode { get; set; }
    }
}
