//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTCN
    {
        public int AbsEntry { get; set; }
        public string CCDNum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CustTerm { get; set; }
        public string CntrOrigin { get; set; }
        public string DirectImp { get; set; }
        public string CardCode { get; set; }
    }
}
