//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTIZ
    {
        public int Id { get; set; }
        public string ChangeDate { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string ActiveDst { get; set; }
        public Nullable<int> offset { get; set; }
    }
}
