//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTRB
    {
        public int AbsEntry { get; set; }
        public Nullable<int> BPLId { get; set; }
        public Nullable<int> GPCId { get; set; }
        public string GPCCode { get; set; }
        public Nullable<short> Year { get; set; }
        public string PrdType { get; set; }
        public Nullable<int> PrdNum { get; set; }
        public Nullable<System.DateTime> PrdDate { get; set; }
        public string RunName { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public string Status { get; set; }
        public string StateTax { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
