//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUDG
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Warehouse { get; set; }
        public Nullable<int> SalePerson { get; set; }
        public string ICTCard { get; set; }
        public string CashAcct { get; set; }
        public string CheckAcct { get; set; }
        public Nullable<short> CreditCard { get; set; }
        public string PrintRcpt { get; set; }
        public string ShortRcpt { get; set; }
        public Nullable<short> Color { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string PrintHeadr { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string E_Mail { get; set; }
        public string FrgnAddr { get; set; }
        public string FrnPrntHdr { get; set; }
        public string FrgnPhone1 { get; set; }
        public string FrgnPhone2 { get; set; }
        public string FrgnFax { get; set; }
        public string DflTaxCode { get; set; }
        public string FreeZoneNo { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string free1 { get; set; }
        public string UseTax { get; set; }
        public string AdrsFromWh { get; set; }
        public Nullable<int> Language { get; set; }
        public string Font { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string AssetInDoc { get; set; }
        public string AttachPath { get; set; }
        public string DflPTICode { get; set; }
        public string Free4 { get; set; }
        public string Free2 { get; set; }
        public string Free3 { get; set; }
        public Nullable<int> DflPosCR { get; set; }
        public string TimeFormat { get; set; }
        public string DateFormat { get; set; }
        public string DateSep { get; set; }
        public string DecSep { get; set; }
        public string ThousSep { get; set; }
        public string WallPaper { get; set; }
        public string WllPprDsp { get; set; }
        public string SkinType { get; set; }
        public Nullable<int> CharMonth { get; set; }
    }
}
