//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUDO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string TableName { get; set; }
        public string LogTable { get; set; }
        public string TYPE { get; set; }
        public string MngSeries { get; set; }
        public string CanDelete { get; set; }
        public string CanClose { get; set; }
        public string CanCancel { get; set; }
        public string ExtName { get; set; }
        public string CanFind { get; set; }
        public string CanYrTrnsf { get; set; }
        public string CanDefForm { get; set; }
        public string CanLog { get; set; }
        public string OvrWrtDll { get; set; }
        public string UIDFormat { get; set; }
        public string CanArchive { get; set; }
        public string MenuItem { get; set; }
        public string MenuCapt { get; set; }
        public Nullable<int> FatherMenu { get; set; }
        public Nullable<short> Position { get; set; }
        public string CanNewForm { get; set; }
        public string IsRebuild { get; set; }
        public string NewFormSrf { get; set; }
        public string MenuUid { get; set; }
        public Nullable<System.DateTime> LstUpdDate { get; set; }
        public Nullable<int> LstUpdTime { get; set; }
        public string CanApprove { get; set; }
        public Nullable<int> TemplateID { get; set; }
    }
}
