//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVTR
    {
        public int AbsEntry { get; set; }
        public string ReportName { get; set; }
        public string RptLayout { get; set; }
        public Nullable<int> FirstPrint { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string TaxDate { get; set; }
        public string RoundSum { get; set; }
        public string Declration { get; set; }
        public string FilterType { get; set; }
        public string ExcludeWT { get; set; }
        public string CustomerIn { get; set; }
        public string VendorIn { get; set; }
        public string Period { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Year { get; set; }
        public string DocType { get; set; }
        public string CreditMemo { get; set; }
        public string DocTypeIn { get; set; }
        public Nullable<int> FirstReg { get; set; }
        public string AccountIn { get; set; }
        public string DeferTaxIn { get; set; }
        public string ApndxOOrP { get; set; }
        public string DispOBCB { get; set; }
        public Nullable<int> FromSeries { get; set; }
        public Nullable<int> ToSeries { get; set; }
        public string canceltn { get; set; }
        public string HideNTrans { get; set; }
        public string SeriesIn { get; set; }
        public string UserCode { get; set; }
        public string FromCardCo { get; set; }
        public string ToCardCo { get; set; }
        public Nullable<int> SizeOfStru { get; set; }
        public Nullable<System.DateTime> PostFrDate { get; set; }
        public Nullable<System.DateTime> PostToDate { get; set; }
        public Nullable<System.DateTime> DocFrDate { get; set; }
        public Nullable<System.DateTime> DocToDate { get; set; }
        public string FromDoc1Nu { get; set; }
        public string ToDoc1Nu { get; set; }
        public string Serie1 { get; set; }
        public string Serie1CB { get; set; }
        public Nullable<int> Doc1Type { get; set; }
        public string FromDoc2Nu { get; set; }
        public string ToDoc2Nu { get; set; }
        public string Serie2 { get; set; }
        public string Serie2CB { get; set; }
        public Nullable<int> Doc2Type { get; set; }
        public string FromDoc3Nu { get; set; }
        public string ToDoc3Nu { get; set; }
        public string Serie3 { get; set; }
        public string Serie3CB { get; set; }
        public Nullable<int> Doc3Type { get; set; }
        public string FromDoc4Nu { get; set; }
        public string ToDoc4Nu { get; set; }
        public string Serie4 { get; set; }
        public string Serie4CB { get; set; }
        public Nullable<int> Doc4Type { get; set; }
        public string FromDoc5Nu { get; set; }
        public string ToDoc5Nu { get; set; }
        public string Serie5 { get; set; }
        public string Serie5CB { get; set; }
        public Nullable<int> Doc5Type { get; set; }
        public string DateRBtn { get; set; }
        public string MarkDocsIn { get; set; }
        public string ExRate { get; set; }
        public string ExRateDate { get; set; }
        public string TrsPerioTp { get; set; }
        public Nullable<int> TrsPerioNu { get; set; }
        public Nullable<short> TrsYear { get; set; }
        public Nullable<short> TrsAdjtNum { get; set; }
        public string DateType { get; set; }
        public string IncServDoc { get; set; }
        public string GrpBySCode { get; set; }
        public string IncUnReDoc { get; set; }
        public string DoYearSum { get; set; }
        public string DefTaxOnly { get; set; }
        public string ExcElDoc { get; set; }
        public string QtrByMnt { get; set; }
    }
}
