//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWDD
    {
        public int WddCode { get; set; }
        public Nullable<int> WtmCode { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string ObjType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> CurrStep { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public string IsDraft { get; set; }
        public Nullable<short> MaxReqr { get; set; }
        public Nullable<short> MaxRejReqr { get; set; }
        public Nullable<int> SrcDocEnt { get; set; }
        public string DraftType { get; set; }
        public Nullable<int> DraftEntry { get; set; }
        public string BFType { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public string ProcesStat { get; set; }
        public string StpUpdated { get; set; }
    }
}
