//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWFER
    {
        public int AbsEntry { get; set; }
        public string MsgID { get; set; }
        public string MsgDetails { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> CreateTime { get; set; }
        public string MsgTaskID { get; set; }
        public string MsgErrSrc { get; set; }
        public string Remark { get; set; }
        public string MsgType { get; set; }
        public Nullable<int> MsgInstID { get; set; }
        public Nullable<int> TemplateID { get; set; }
    }
}
