//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWKO
    {
        public int OrderNum { get; set; }
        public string Status { get; set; }
        public string Canceled { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ProdctDate { get; set; }
        public Nullable<System.DateTime> ExpFinishD { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string FinishUser { get; set; }
        public string CardCode { get; set; }
        public string CustomName { get; set; }
        public string NumInCustm { get; set; }
        public Nullable<decimal> TotalOrder { get; set; }
        public string TotalCurr { get; set; }
        public Nullable<short> DocTime { get; set; }
        public string Memo { get; set; }
        public int SerialNum { get; set; }
        public Nullable<int> CntctCode { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Transfered { get; set; }
        public short Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string ActWorkCod { get; set; }
        public Nullable<decimal> ActWorkSum { get; set; }
        public string JrnlMemo { get; set; }
        public string DataSource { get; set; }
        public string ObjType { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> PriceList { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public Nullable<decimal> SysRate { get; set; }
    }
}
