//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL
    {
        public Nullable<int> WFInstID { get; set; }
        public int TaskID { get; set; }
        public string WFID { get; set; }
        public string WFName { get; set; }
        public string TaskDesc { get; set; }
        public string ObjType { get; set; }
        public string Operation { get; set; }
        public string ObjKey { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<short> EnterTime { get; set; }
        public string TaskType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<short> DueTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string Owner { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string Status { get; set; }
        public Nullable<int> LogIns { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public string Deleted { get; set; }
        public Nullable<int> DuraDays { get; set; }
        public Nullable<short> DuraHours { get; set; }
        public string TaskName { get; set; }
        public string isPicked { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public Nullable<int> WorkListId { get; set; }
        public string ObjSubType { get; set; }
        public string ForwardTo { get; set; }
        public string WasRead { get; set; }
        public string TrigParams { get; set; }
        public string Key { get; set; }
    }
}
