//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWTI
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> RepeatCnt { get; set; }
        public string Duration { get; set; }
        public string LastUpdate { get; set; }
        public Nullable<System.DateTime> UnScheStDt { get; set; }
        public Nullable<int> UnScheStTi { get; set; }
        public Nullable<int> UnScheReCt { get; set; }
        public string IsComplete { get; set; }
        public string JobHanType { get; set; }
        public string JobHanConf { get; set; }
        public string IsActive { get; set; }
    }
}
