//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OZRD
    {
        public int AbsEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string POSEquipNo { get; set; }
        public Nullable<int> ResetCntr { get; set; }
        public Nullable<int> SummaryCnt { get; set; }
        public Nullable<int> OperCntr { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<decimal> GrossSale { get; set; }
        public Nullable<decimal> PISSum { get; set; }
        public Nullable<decimal> COFINSSum { get; set; }
    }
}
