//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACT
    {
        public int AbsEntry { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string TgtObjId { get; set; }
        public string SrcObjId { get; set; }
        public string SrcType { get; set; }
    }
}
