//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDF3
    {
        public int DocNum { get; set; }
        public int LineID { get; set; }
        public Nullable<short> CreditCard { get; set; }
        public string CreditAcct { get; set; }
        public string CrCardNum { get; set; }
        public Nullable<System.DateTime> CardValid { get; set; }
        public string VoucherNum { get; set; }
        public string OwnerIdNum { get; set; }
        public string OwnerPhone { get; set; }
        public Nullable<short> CrTypeCode { get; set; }
        public Nullable<short> NumOfPmnts { get; set; }
        public Nullable<System.DateTime> FirstDue { get; set; }
        public Nullable<decimal> FirstSum { get; set; }
        public Nullable<decimal> AddPmntSum { get; set; }
        public Nullable<decimal> CreditSum { get; set; }
        public string CreditCur { get; set; }
        public Nullable<decimal> CreditRate { get; set; }
        public string ConfNum { get; set; }
        public string CreditType { get; set; }
        public Nullable<short> CredPmnts { get; set; }
        public string PlCrdStat { get; set; }
        public string MagnetStr { get; set; }
        public string SpiltCred { get; set; }
        public Nullable<int> ConsolNum { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string EncryptIV { get; set; }
    }
}
