//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHA4
    {
        public int AbsEntry { get; set; }
        public int LineID { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<int> TYP { get; set; }
        public Nullable<int> DOCNUM { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string Status { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string AmountCat { get; set; }
        public string Categorize { get; set; }
        public string Operation { get; set; }
        public string Chargeable { get; set; }
        public Nullable<decimal> Charged { get; set; }
        public Nullable<decimal> ChargedQty { get; set; }
        public string DocType { get; set; }
        public string EncryptIV { get; set; }
    }
}
