//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMG1
    {
        public int AbsEntry { get; set; }
        public int LineID { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<int> POS { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<System.DateTime> CLOSE { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public Nullable<int> Task { get; set; }
        public string DSCRIPTION { get; set; }
        public Nullable<decimal> EXPCOSTS { get; set; }
        public Nullable<decimal> InvAmtAR { get; set; }
        public Nullable<decimal> OpenAmtAR { get; set; }
        public Nullable<decimal> InvAmtAP { get; set; }
        public Nullable<decimal> OpenAmtAP { get; set; }
        public Nullable<decimal> PERCENT { get; set; }
        public string FINISH { get; set; }
        public Nullable<int> OWNER { get; set; }
        public Nullable<int> StageDep1 { get; set; }
        public Nullable<int> StageDep2 { get; set; }
        public Nullable<int> StageDep3 { get; set; }
        public Nullable<int> StageDep4 { get; set; }
        public string StDp1Type { get; set; }
        public string StDp2Type { get; set; }
        public string StDp3Type { get; set; }
        public string StDp4Type { get; set; }
        public Nullable<int> StDp1Abs { get; set; }
        public Nullable<int> StDp2Abs { get; set; }
        public Nullable<int> StDp3Abs { get; set; }
        public Nullable<int> StDp4Abs { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public string UniqueID { get; set; }
        public string EncryptIV { get; set; }
    }
}
