//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMG2
    {
        public int AbsEntry { get; set; }
        public int LineID { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<int> AREA { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string REMARKS { get; set; }
        public string CLOSED { get; set; }
        public Nullable<int> SOLUTIONID { get; set; }
        public string SOLUTION { get; set; }
        public Nullable<int> RESPNSIBLE { get; set; }
        public Nullable<int> ENTERED { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<decimal> EFFORT { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string EncryptIV { get; set; }
    }
}
