//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWZ6
    {
        public int IdEntry { get; set; }
        public int CondNum { get; set; }
        public string SelFldID { get; set; }
        public string FromString { get; set; }
        public Nullable<int> FromNumber { get; set; }
        public Nullable<decimal> FromMoney { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string FromMemo { get; set; }
        public string ToString { get; set; }
        public Nullable<int> ToNumber { get; set; }
        public Nullable<decimal> ToMoney { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ToMemo { get; set; }
    }
}
