//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class QWZ3
    {
        public string Code { get; set; }
        public int Numerator { get; set; }
        public Nullable<int> OpenBrackt { get; set; }
        public string FileCode { get; set; }
        public string FieldAlias { get; set; }
        public Nullable<int> Operation { get; set; }
        public string CondVal { get; set; }
        public string CondEndVal { get; set; }
        public string CompareFld { get; set; }
        public string UseRes { get; set; }
        public string CompTblIdx { get; set; }
        public string CompFldNum { get; set; }
        public Nullable<int> Relatship { get; set; }
        public Nullable<int> ClosBrackt { get; set; }
        public string Free_Text { get; set; }
    }
}
