//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCON
    {
        public string DocCode { get; set; }
        public int ConnID { get; set; }
        public string OldServer { get; set; }
        public string OldDbName { get; set; }
        public string NewServer { get; set; }
        public string NewDbName { get; set; }
        public string UserCode { get; set; }
        public Nullable<short> SubIndex { get; set; }
        public string SubName { get; set; }
    }
}
