//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCR1
    {
        public string RcurCode { get; set; }
        public int LineId { get; set; }
        public string AcctCode { get; set; }
        public string AcctDesc { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Currency { get; set; }
        public short Instance { get; set; }
        public string VatGroup { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string VatLine { get; set; }
        public string CtrlAcct { get; set; }
        public string OcrCode { get; set; }
        public Nullable<short> TaxType { get; set; }
        public string TaxPostAcc { get; set; }
        public string StaCode { get; set; }
        public Nullable<int> StaType { get; set; }
        public string TaxCode { get; set; }
        public string OcrCode1 { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string WtLiable { get; set; }
        public string WTaxLine { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public string Project { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string CemCode { get; set; }
    }
}
