//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDR18
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> ExpDocType { get; set; }
        public Nullable<int> ExpDeclNum { get; set; }
        public Nullable<System.DateTime> ExpDeclDat { get; set; }
        public Nullable<int> ExpNature { get; set; }
        public Nullable<int> ExpRegNum { get; set; }
        public Nullable<System.DateTime> ExpRegDate { get; set; }
        public string LadBillNum { get; set; }
        public Nullable<System.DateTime> LadBillDat { get; set; }
        public Nullable<System.DateTime> MerchLeftD { get; set; }
        public Nullable<int> LadBillTyp { get; set; }
    }
}
