//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQ1
    {
        public int AbsEntry { get; set; }
        public int LineId { get; set; }
        public string MsgType { get; set; }
        public string ErrCode { get; set; }
        public string MsgBody { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
        public Nullable<int> MsgTime { get; set; }
    }
}
