//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL1
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<decimal> PackQty { get; set; }
        public string PurPackMsr { get; set; }
        public string ArsnalName { get; set; }
        public string ArsnalCode { get; set; }
        public string UnitMsr { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Fraction { get; set; }
        public Nullable<decimal> Weight1 { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public string ItemCode { get; set; }
    }
}
