//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFC6
    {
        public int DocEntry { get; set; }
        public short InstlmntID { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> DunnLevel { get; set; }
        public Nullable<decimal> InsTotal { get; set; }
        public Nullable<decimal> InsTotalFC { get; set; }
        public Nullable<decimal> InsTotalSy { get; set; }
        public Nullable<decimal> PaidToDate { get; set; }
        public Nullable<decimal> PaidFC { get; set; }
        public Nullable<decimal> PaidSys { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> VatSumFC { get; set; }
        public Nullable<decimal> VatSumSy { get; set; }
        public Nullable<decimal> VatPaid { get; set; }
        public Nullable<decimal> VatPaidFC { get; set; }
        public Nullable<decimal> VatPaidSys { get; set; }
        public Nullable<decimal> TotalExpns { get; set; }
        public Nullable<decimal> TotalExpFC { get; set; }
        public Nullable<decimal> TotalExpSC { get; set; }
        public Nullable<decimal> ExpAppl { get; set; }
        public Nullable<decimal> ExpApplFC { get; set; }
        public Nullable<decimal> ExpApplSC { get; set; }
        public Nullable<decimal> WTSum { get; set; }
        public Nullable<decimal> WTSumFC { get; set; }
        public Nullable<decimal> WTSumSC { get; set; }
        public Nullable<decimal> WTApplied { get; set; }
        public Nullable<decimal> WTAppliedF { get; set; }
        public Nullable<decimal> WTAppliedS { get; set; }
        public Nullable<decimal> TotalBlck { get; set; }
        public Nullable<decimal> TotalBlckF { get; set; }
        public Nullable<decimal> TotalBlckS { get; set; }
        public Nullable<decimal> VATBlck { get; set; }
        public Nullable<decimal> VATBlckFC { get; set; }
        public Nullable<decimal> VATBlckSC { get; set; }
        public Nullable<decimal> ExpnsBlck { get; set; }
        public Nullable<decimal> ExpnsBlckF { get; set; }
        public Nullable<decimal> ExpnsBlckS { get; set; }
        public Nullable<decimal> WTBlocked { get; set; }
        public Nullable<decimal> WTBlockedF { get; set; }
        public Nullable<decimal> WTBlockedS { get; set; }
        public Nullable<decimal> InstPrcnt { get; set; }
        public string DunWizBlck { get; set; }
        public Nullable<System.DateTime> DunDate { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> PaidFrgn { get; set; }
        public Nullable<decimal> PaidSc { get; set; }
        public string reserved { get; set; }
        public Nullable<decimal> TaxOnExp { get; set; }
        public Nullable<decimal> TaxOnExpFc { get; set; }
        public Nullable<decimal> TaxOnExpSc { get; set; }
        public Nullable<decimal> TaxOnExpAp { get; set; }
        public Nullable<decimal> TaxOnExApF { get; set; }
        public Nullable<decimal> TaxOnExApS { get; set; }
        public Nullable<decimal> TaxOnExBlo { get; set; }
        public Nullable<decimal> TaxOnExBlF { get; set; }
        public Nullable<decimal> TaxOnExBlS { get; set; }
        public Nullable<System.DateTime> LvlUpdDate { get; set; }
        public string Ordered { get; set; }
        public Nullable<decimal> PaidDpm { get; set; }
        public Nullable<decimal> PaidDpmFc { get; set; }
        public Nullable<decimal> PaidDpmSc { get; set; }
        public string EncryptIV { get; set; }
    }
}
