//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHR1
    {
        public int ShrId { get; set; }
        public int RowId { get; set; }
        public Nullable<short> CatId { get; set; }
        public string LineNum { get; set; }
        public string ItemName { get; set; }
        public Nullable<short> Level { get; set; }
        public string IndentChar { get; set; }
        public string Formula { get; set; }
        public Nullable<decimal> CurAmount { get; set; }
        public Nullable<decimal> PreAmount { get; set; }
    }
}
