//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI3
    {
        public int WizardId { get; set; }
        public int SOINum { get; set; }
        public Nullable<int> AgrNum { get; set; }
        public Nullable<int> AgrNo { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string PayToCtry { get; set; }
        public Nullable<int> PmntNum { get; set; }
        public Nullable<int> PmntEntry { get; set; }
        public Nullable<int> PmntType { get; set; }
        public Nullable<System.DateTime> PmntDate { get; set; }
        public Nullable<decimal> ExcBasSum { get; set; }
        public Nullable<decimal> ExciseSum { get; set; }
        public Nullable<decimal> VatBaseSum { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string ExecStat { get; set; }
        public Nullable<int> BPLId { get; set; }
    }
}
