//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOI4
    {
        public int WizardId { get; set; }
        public int SOINum { get; set; }
        public int DocType { get; set; }
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string NumAtCard { get; set; }
        public Nullable<int> InvEntry { get; set; }
    }
}
