//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRA3
    {
        public int ActionCode { get; set; }
        public int RecipCode { get; set; }
        public string ObjType { get; set; }
        public string ObjCode { get; set; }
        public string Name { get; set; }
        public string SendInter { get; set; }
        public string SendEmail { get; set; }
        public string SendSMS { get; set; }
        public string Email { get; set; }
        public string Number { get; set; }
        public string AttachDAG { get; set; }
        public string AttachPDF { get; set; }
        public string AttachHTML { get; set; }
        public string AttachXML { get; set; }
        public string ShowResult { get; set; }
    }
}
