//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCD5
    {
        public int AbsId { get; set; }
        public Nullable<int> Tcd3Id { get; set; }
        public Nullable<int> UsageCode { get; set; }
        public string TaxCode { get; set; }
        public string Type { get; set; }
        public string ExpTaxCode { get; set; }
        public string PurTaxCode { get; set; }
    }
}
