//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCN3
    {
        public int AbsEntry { get; set; }
        public int LineNum { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> QtyOnHand { get; set; }
    }
}
