//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDR1
    {
        public int Line_ID { get; set; }
        public string KeySeg1 { get; set; }
        public string KeySeg2 { get; set; }
        public string KeySeg3 { get; set; }
        public string KeySeg4 { get; set; }
        public string KeySeg5 { get; set; }
        public string KeySeg6 { get; set; }
        public string KeySeg7 { get; set; }
        public string KeySeg8 { get; set; }
        public string KeySeg9 { get; set; }
        public string KeySeg10 { get; set; }
        public Nullable<int> DocAbs { get; set; }
    }
}
