//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFC1
    {
        public int TfcId { get; set; }
        public int DispOrder { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> FmlId { get; set; }
    }
}
