//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGPA
    {
        public int AbsEntry { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> LineID { get; set; }
        public string Selected { get; set; }
        public string DocType { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> DocAbs { get; set; }
        public Nullable<int> DocLineNum { get; set; }
        public Nullable<int> ManagedBy { get; set; }
        public Nullable<int> SysNumber { get; set; }
    }
}
