//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIBT1
    {
        public string ItemCode { get; set; }
        public string BatchNum { get; set; }
        public string WhsCode { get; set; }
        public int LineNum { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseNum { get; set; }
        public Nullable<int> BaseLinNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Direction { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> BsDocType { get; set; }
        public Nullable<int> BsDocEntry { get; set; }
        public Nullable<int> BsDocLine { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string UpgCurNode { get; set; }
        public string UpgParent { get; set; }
        public Nullable<int> UpgSortId { get; set; }
    }
}
