//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPW2
    {
        public int AbsEntry { get; set; }
        public int LineNumber { get; set; }
        public Nullable<int> TaxCategry { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<decimal> PyblAmnt { get; set; }
        public Nullable<decimal> PyblAmntFC { get; set; }
        public Nullable<decimal> PyblAmntSC { get; set; }
        public Nullable<decimal> PLAAmnt { get; set; }
        public Nullable<decimal> PLAAmntFC { get; set; }
        public Nullable<decimal> PLAAmntSC { get; set; }
    }
}
