//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPW5
    {
        public int AbsEntry { get; set; }
        public Nullable<System.DateTime> ChlnDate { get; set; }
        public string ChlnNo { get; set; }
        public string ChlnBank { get; set; }
        public string ChlnMemo { get; set; }
    }
}
