//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRO1
    {
        public int AbsEntry { get; set; }
        public int LineNum { get; set; }
        public int DocObjType { get; set; }
        public int DocEntry { get; set; }
        public int DocLineNum { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> TranspQty { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<int> DocOrdNum { get; set; }
    }
}
