//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTP1
    {
        public short UserSign { get; set; }
        public int ObjectId { get; set; }
        public string DataKey { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string IsVisible { get; set; }
    }
}
