//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDG1
    {
        public string Code { get; set; }
        public string ObjType { get; set; }
        public Nullable<short> Copies { get; set; }
        public string PrintOnAdd { get; set; }
        public string ExprtOnAdd { get; set; }
        public string RoundSums { get; set; }
        public string Remark { get; set; }
        public string PrintSums { get; set; }
        public string VndrNum { get; set; }
        public string PrnDscnt { get; set; }
        public Nullable<short> HandCopies { get; set; }
        public string EngKBItem { get; set; }
        public string EngKBCard { get; set; }
        public string EmailOnAdd { get; set; }
        public string PDFOnAdd { get; set; }
    }
}
