//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDO1
    {
        public string Code { get; set; }
        public int SonNum { get; set; }
        public string TableName { get; set; }
        public string LogName { get; set; }
        public string SonName { get; set; }
    }
}
