//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIC2
    {
        public short TPLId { get; set; }
        public string FormId { get; set; }
        public string ItemId { get; set; }
        public string Visible { get; set; }
        public string VisibleCtl { get; set; }
        public string Editable { get; set; }
        public string EditbleCtl { get; set; }
        public Nullable<short> Left { get; set; }
        public Nullable<short> Top { get; set; }
        public Nullable<short> Right { get; set; }
        public Nullable<short> Bottom { get; set; }
        public Nullable<short> FromPane { get; set; }
        public Nullable<short> ToPane { get; set; }
        public string UDF { get; set; }
        public string TableName { get; set; }
    }
}
