//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIVL1
    {
        public int TransSeq { get; set; }
        public int LayerID { get; set; }
        public Nullable<decimal> CalcPrice { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> TransValue { get; set; }
        public Nullable<decimal> LayerInQty { get; set; }
        public Nullable<decimal> LayerOutQ { get; set; }
        public Nullable<decimal> RevalTotal { get; set; }
    }
}
