//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIVQ
    {
        public Nullable<int> TreeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<short> LocType { get; set; }
        public string LocCode { get; set; }
        public int TransSeq { get; set; }
        public int LayerID { get; set; }
        public Nullable<decimal> OpenQty { get; set; }
        public Nullable<decimal> OpenValue { get; set; }
        public string ItemCode { get; set; }
        public int AbsEntry { get; set; }
        public Nullable<int> StockActio { get; set; }
        public string RemMethod { get; set; }
    }
}
