//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKD1
    {
        public string TableName { get; set; }
        public short KeyId { get; set; }
        public short SubKeyId { get; set; }
        public string ColAlias { get; set; }
    }
}
