//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR1
    {
        public string STATUS { get; set; }
        public short USERLINK { get; set; }
        public string MODIF01 { get; set; }
        public string MODIF02 { get; set; }
        public string MODIF03 { get; set; }
        public string MODIF04 { get; set; }
        public string MODIF05 { get; set; }
        public string MODIF06 { get; set; }
        public string MODIF07 { get; set; }
        public string MODIF08 { get; set; }
        public string MODIF09 { get; set; }
        public string MODIF10 { get; set; }
        public string MODIF11 { get; set; }
        public string MODIF12 { get; set; }
        public string MODIF13 { get; set; }
        public Nullable<int> ATOMID01 { get; set; }
        public Nullable<int> ATOMID02 { get; set; }
        public Nullable<int> ATOMID03 { get; set; }
        public Nullable<int> ATOMID04 { get; set; }
        public Nullable<int> ATOMID05 { get; set; }
        public Nullable<int> ATOMID06 { get; set; }
        public Nullable<int> ATOMID07 { get; set; }
        public Nullable<int> ATOMID08 { get; set; }
        public Nullable<int> ATOMID09 { get; set; }
        public Nullable<int> ATOMID10 { get; set; }
        public Nullable<int> ATOMID11 { get; set; }
        public Nullable<int> ATOMID12 { get; set; }
        public Nullable<int> ATOMID13 { get; set; }
        public Nullable<int> STRID01 { get; set; }
        public Nullable<int> STRID02 { get; set; }
        public Nullable<int> STRID03 { get; set; }
        public Nullable<int> STRID04 { get; set; }
        public Nullable<int> STRID05 { get; set; }
        public Nullable<int> STRID06 { get; set; }
        public Nullable<int> STRID07 { get; set; }
        public Nullable<int> STRID08 { get; set; }
        public Nullable<int> STRID09 { get; set; }
        public Nullable<int> STRID10 { get; set; }
        public Nullable<int> STRID11 { get; set; }
        public Nullable<int> STRID12 { get; set; }
        public Nullable<int> STRID13 { get; set; }
        public string RESERVED { get; set; }
        public string FILLER { get; set; }
    }
}
