//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR2
    {
        public string USER_CODE { get; set; }
        public string PATH1 { get; set; }
        public string PATH2 { get; set; }
        public string PATH3 { get; set; }
        public string PATH4 { get; set; }
        public string PATH5 { get; set; }
        public string PATH6 { get; set; }
        public string PATH7 { get; set; }
        public string PATH8 { get; set; }
        public string PATH9 { get; set; }
        public string PATH10 { get; set; }
    }
}
