//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USRN
    {
        public string ItemCode { get; set; }
        public int SysNumber { get; set; }
        public string DistNumber { get; set; }
        public string MnfSerial { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> MnfDate { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> GrntStart { get; set; }
        public Nullable<System.DateTime> GrntExp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
        public int AbsEntry { get; set; }
        public string ObjType { get; set; }
        public string itemName { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> CostTotal { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantOut { get; set; }
        public Nullable<decimal> PriceDiff { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> TrackingNt { get; set; }
        public Nullable<int> TrackiNtLn { get; set; }
        public Nullable<short> SumDec { get; set; }
    }
}
