//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UXILM
    {
        public int MessageID { get; set; }
        public Nullable<int> MinMsgID { get; set; }
        public Nullable<int> MaxMsgID { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocLineNum { get; set; }
        public Nullable<int> TransType { get; set; }
    }
}
