//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTR1
    {
        public int AbsEntry { get; set; }
        public string ObjectCode { get; set; }
        public string Sum { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string ObjectType { get; set; }
        public string Selected { get; set; }
        public string FromObject { get; set; }
        public string ToObject { get; set; }
        public string Adtnl_Key { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
