//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTR2
    {
        public int AbsEntry { get; set; }
        public string ObjectCode { get; set; }
        public Nullable<int> FromDocNo { get; set; }
        public Nullable<int> ToDocNo { get; set; }
        public string Selected { get; set; }
    }
}
