//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WDD2
    {
        public int WddCode { get; set; }
        public int CondId { get; set; }
        public Nullable<short> opCode { get; set; }
        public string opValue { get; set; }
    }
}
