//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WKO1
    {
        public int OrderNum { get; set; }
        public int LineID { get; set; }
        public string ItemCode { get; set; }
        public string Descript { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public string WhsCode { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public string ActWorkCod { get; set; }
        public Nullable<decimal> ActWorkSum { get; set; }
        public Nullable<int> ProdUpgNum { get; set; }
    }
}
