//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WLS2
    {
        public Nullable<int> WFInstID { get; set; }
        public int TaskID { get; set; }
        public int LineID { get; set; }
        public string ObjectType { get; set; }
        public string ObjKey { get; set; }
        public string Command { get; set; }
        public Nullable<int> LogIns { get; set; }
        public string ObjSubType { get; set; }
        public string ObjDetail { get; set; }
    }
}
