//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WPK3
    {
        public int AbsEntry { get; set; }
        public Nullable<int> DsbrdEntry { get; set; }
        public string FldName { get; set; }
        public string FldMethod { get; set; }
        public string DbType { get; set; }
        public Nullable<int> SqlType { get; set; }
    }
}
