//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WTQ15
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ObjType { get; set; }
        public int LogInstanc { get; set; }
        public string VatGroup { get; set; }
        public string StaCode { get; set; }
        public Nullable<int> StaType { get; set; }
        public Nullable<int> StaIndex { get; set; }
        public Nullable<decimal> BaseNet { get; set; }
        public Nullable<decimal> BaseNetFc { get; set; }
        public Nullable<decimal> BaseNetSc { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> VatSumFc { get; set; }
        public Nullable<decimal> VatSumSc { get; set; }
        public Nullable<decimal> DctSum { get; set; }
        public Nullable<decimal> DctSumFc { get; set; }
        public Nullable<decimal> DctSumSc { get; set; }
        public Nullable<decimal> EqSum { get; set; }
        public Nullable<decimal> EqSumFc { get; set; }
        public Nullable<decimal> EqSumSc { get; set; }
        public Nullable<decimal> ApplNet { get; set; }
        public Nullable<decimal> ApplNetFc { get; set; }
        public Nullable<decimal> ApplNetSc { get; set; }
        public Nullable<decimal> ApplVat { get; set; }
        public Nullable<decimal> ApplVatFc { get; set; }
        public Nullable<decimal> ApplVatSc { get; set; }
        public Nullable<decimal> ApplDct { get; set; }
        public Nullable<decimal> ApplDctFc { get; set; }
        public Nullable<decimal> ApplDctSc { get; set; }
        public Nullable<decimal> ApplEq { get; set; }
        public Nullable<decimal> ApplEqFc { get; set; }
        public Nullable<decimal> ApplEqSc { get; set; }
        public Nullable<decimal> PaidNet { get; set; }
        public Nullable<decimal> PaidNetFc { get; set; }
        public Nullable<decimal> PaidNetSc { get; set; }
        public Nullable<decimal> PaidVat { get; set; }
        public Nullable<decimal> PaidVatFc { get; set; }
        public Nullable<decimal> PaidVatSc { get; set; }
        public Nullable<decimal> PaidDct { get; set; }
        public Nullable<decimal> PaidDctFc { get; set; }
        public Nullable<decimal> PaidDctSc { get; set; }
        public Nullable<decimal> PaidEq { get; set; }
        public Nullable<decimal> PaidEqFc { get; set; }
        public Nullable<decimal> PaidEqSc { get; set; }
        public Nullable<decimal> DpApplNet { get; set; }
        public Nullable<decimal> DpApplNetF { get; set; }
        public Nullable<decimal> DpApplNetS { get; set; }
        public Nullable<decimal> DpApplVat { get; set; }
        public Nullable<decimal> DpApplVatF { get; set; }
        public Nullable<decimal> DpApplVatS { get; set; }
        public Nullable<decimal> DpApplDct { get; set; }
        public Nullable<decimal> DpApplDctF { get; set; }
        public Nullable<decimal> DpApplDctS { get; set; }
        public Nullable<decimal> DpApplEq { get; set; }
        public Nullable<decimal> DpApplEqFc { get; set; }
        public Nullable<decimal> DpApplEqSc { get; set; }
        public string TaxCode { get; set; }
        public string LineType { get; set; }
        public Nullable<decimal> BaseGrs { get; set; }
        public Nullable<decimal> BaseGrsFc { get; set; }
        public Nullable<decimal> BaseGrsSc { get; set; }
        public Nullable<decimal> ApplGrs { get; set; }
        public Nullable<decimal> ApplGrsFc { get; set; }
        public Nullable<decimal> ApplGrsSc { get; set; }
        public Nullable<decimal> PaidGrs { get; set; }
        public Nullable<decimal> PaidGrsFc { get; set; }
        public Nullable<decimal> PaidGrsSc { get; set; }
        public Nullable<decimal> DpApplGrs { get; set; }
        public Nullable<decimal> DpApplGrsF { get; set; }
        public Nullable<decimal> DpApplGrsS { get; set; }
        public Nullable<decimal> RvsChrgSum { get; set; }
        public Nullable<decimal> RvsChrgSc { get; set; }
        public Nullable<decimal> RvsChrgFc { get; set; }
        public Nullable<decimal> ApplRvs { get; set; }
        public Nullable<decimal> ApplRvsSc { get; set; }
        public Nullable<decimal> ApplRvsFc { get; set; }
        public Nullable<decimal> PaidRvs { get; set; }
        public Nullable<decimal> PaidRvsSc { get; set; }
        public Nullable<decimal> PaidRvsFc { get; set; }
        public Nullable<decimal> DpApplRvs { get; set; }
        public Nullable<decimal> DpApplRvsS { get; set; }
        public Nullable<decimal> DpApplRvsF { get; set; }
        public string IsPrscGood { get; set; }
        public string IsCstmAct { get; set; }
    }
}
