//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WTQ3
    {
        public int DocEntry { get; set; }
        public Nullable<int> ExpnsCode { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<decimal> TotalFrgn { get; set; }
        public Nullable<decimal> TotalSumSy { get; set; }
        public Nullable<decimal> PaidToDate { get; set; }
        public Nullable<decimal> PaidFC { get; set; }
        public Nullable<decimal> PaidSys { get; set; }
        public string Comments { get; set; }
        public string ObjType { get; set; }
        public int LogInstanc { get; set; }
        public string DistrbMthd { get; set; }
        public string TaxStatus { get; set; }
        public string VatGroup { get; set; }
        public Nullable<decimal> VatPrcnt { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> VatSumFrgn { get; set; }
        public Nullable<decimal> VatSumSy { get; set; }
        public Nullable<decimal> DedVatSum { get; set; }
        public Nullable<decimal> DedVatSumF { get; set; }
        public Nullable<decimal> DedVatSumS { get; set; }
        public string IsAcquistn { get; set; }
        public string TaxCode { get; set; }
        public string TaxType { get; set; }
        public string WTLiable { get; set; }
        public Nullable<decimal> VatApplied { get; set; }
        public Nullable<decimal> VatAppldFC { get; set; }
        public Nullable<decimal> VatAppldSC { get; set; }
        public Nullable<decimal> EquVatPer { get; set; }
        public Nullable<decimal> EquVatSum { get; set; }
        public Nullable<decimal> EquVatSumF { get; set; }
        public Nullable<decimal> EquVatSumS { get; set; }
        public Nullable<decimal> LineVat { get; set; }
        public Nullable<decimal> LineVatF { get; set; }
        public Nullable<decimal> LineVatS { get; set; }
        public string BaseMethod { get; set; }
        public string Stock { get; set; }
        public string LstPchPrce { get; set; }
        public string AnalysRpt { get; set; }
        public Nullable<int> BaseAbsEnt { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> BaseRef { get; set; }
        public Nullable<int> BaseLnNum { get; set; }
        public int LineNum { get; set; }
        public string Status { get; set; }
        public Nullable<int> TrgType { get; set; }
        public Nullable<int> TrgAbsEnt { get; set; }
        public Nullable<decimal> StDstr { get; set; }
        public Nullable<decimal> StDstrSC { get; set; }
        public Nullable<decimal> StDstrFC { get; set; }
        public string FixCurr { get; set; }
        public Nullable<decimal> VatDscntPr { get; set; }
        public string OcrCode { get; set; }
        public string TaxDistMtd { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string Project { get; set; }
        public string VatGrpSrc { get; set; }
        public Nullable<decimal> DrawnTotal { get; set; }
        public Nullable<decimal> DrawnFC { get; set; }
        public Nullable<decimal> DrawnSC { get; set; }
        public Nullable<decimal> GrsAmount { get; set; }
        public Nullable<decimal> GrsFC { get; set; }
        public Nullable<decimal> GrsSC { get; set; }
        public string BaseTotal { get; set; }
        public Nullable<decimal> RetReqLC { get; set; }
        public Nullable<decimal> RetReqFC { get; set; }
        public Nullable<decimal> RetReqSC { get; set; }
        public Nullable<decimal> RRVatLC { get; set; }
        public Nullable<decimal> RRVatFC { get; set; }
        public Nullable<decimal> RRVatSC { get; set; }
        public string EncryptIV { get; set; }
    }
}
