//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class XAP1
    {
        public int AbsEntry { get; set; }
        public Nullable<int> XAPEntry { get; set; }
        public string Name { get; set; }
        public string Default { get; set; }
    }
}
