//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZRD1
    {
        public int AbsEntry { get; set; }
        public int LineNum { get; set; }
        public string Code { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public string Descriptn { get; set; }
    }
}
